/**
 * LocationNames.cpp - Met-location name lookup (per generation)
 *
 * Auto-generated by tools/gen_locations.py from PKHeX's met-location text
 * resources (PKHeX.Core/Resources/text/locations/.../text_*_00000_en.txt).
 * Each table is the MAIN (0x0-based) met-location list for one game group;
 * a location ID indexes directly into the table.
 *
 * The same numeric location ID names a DIFFERENT place in each generation,
 * so callers must pass the mon's ORIGIN game-version id (see Enums::GameVersion)
 * to select the correct table.
 *
 * Blank slots and PKHeX's em-dash "no location" sentinel are emitted as "".
 */

#include "Names/LocationNames.h"

#include <cstddef>

namespace Names {

    // Let's Go, Pikachu! / Eevee! (GP=42, GE=43)
    // Source: PKHeX text_gg_00000_en.txt  (54 entries)
    static const char* const GG_LOC_NAMES[] = {
        "",  // 0
        "Mystery Zone",  // 1
        "Faraway place",  // 2
        "Route 1",  // 3
        "Route 2",  // 4
        "Route 3",  // 5
        "Route 4",  // 6
        "Route 5",  // 7
        "Route 6",  // 8
        "Route 7",  // 9
        "Route 8",  // 10
        "Route 9",  // 11
        "Route 10",  // 12
        "Route 11",  // 13
        "Route 12",  // 14
        "Route 13",  // 15
        "Route 14",  // 16
        "Route 15",  // 17
        "Route 16",  // 18
        "Route 17",  // 19
        "Route 18",  // 20
        "Route 19",  // 21
        "Route 20",  // 22
        "Route 21",  // 23
        "Route 22",  // 24
        "Route 23",  // 25
        "Route 24",  // 26
        "Route 25",  // 27
        "Pallet Town",  // 28
        "Viridian City",  // 29
        "Pewter City",  // 30
        "Cerulean City",  // 31
        "Lavender Town",  // 32
        "Vermilion City",  // 33
        "Celadon City",  // 34
        "Fuchsia City",  // 35
        "Cinnabar Island",  // 36
        "Indigo Plateau",  // 37
        "Saffron City",  // 38
        "Viridian Forest",  // 39
        "Mt. Moon",  // 40
        "Rock Tunnel",  // 41
        "Power Plant",  // 42
        "Diglett’s Cave",  // 43
        "Seafoam Islands",  // 44
        "Victory Road",  // 45
        "Cerulean Cave",  // 46
        "Pokémon Tower",  // 47
        "S.S. Anne",  // 48
        "Team Rocket Hideout",  // 49
        "GO Park complex",  // 50
        "Pokémon Mansion",  // 51
        "Silph Co.",  // 52
        "Pokémon League",  // 53
    };

    // Sword / Shield (SW=44, SH=45)
    // Source: PKHeX text_swsh_00000_en.txt  (247 entries)
    static const char* const SWSH_LOC_NAMES[] = {
        "",  // 0
        "",  // 1
        "Mystery Zone",  // 2
        "",  // 3
        "Faraway place",  // 4
        "",  // 5
        "Postwick",  // 6
        "",  // 7
        "Slumbering Weald",  // 8
        "",  // 9
        "",  // 10
        "",  // 11
        "Route 1",  // 12
        "",  // 13
        "Wedgehurst",  // 14
        "",  // 15
        "Wedgehurst Station",  // 16
        "",  // 17
        "Route 2",  // 18
        "",  // 19
        "Motostoke",  // 20
        "",  // 21
        "Motostoke Station",  // 22
        "",  // 23
        "Motostoke Stadium",  // 24
        "",  // 25
        "",  // 26
        "",  // 27
        "Route 3",  // 28
        "",  // 29
        "Galar Mine",  // 30
        "",  // 31
        "Route 4",  // 32
        "",  // 33
        "Turffield",  // 34
        "",  // 35
        "Turffield Stadium",  // 36
        "",  // 37
        "",  // 38
        "",  // 39
        "Route 5",  // 40
        "",  // 41
        "",  // 42
        "",  // 43
        "Hulbury",  // 44
        "",  // 45
        "Hulbury Station",  // 46
        "",  // 47
        "Hulbury Stadium",  // 48
        "",  // 49
        "",  // 50
        "",  // 51
        "Motostoke Outskirts",  // 52
        "",  // 53
        "Galar Mine No. 2",  // 54
        "",  // 55
        "Hammerlocke",  // 56
        "",  // 57
        "Hammerlocke Station",  // 58
        "",  // 59
        "Hammerlocke Stadium",  // 60
        "",  // 61
        "",  // 62
        "",  // 63
        "Energy Plant",  // 64
        "",  // 65
        "Tower Summit",  // 66
        "",  // 67
        "Route 6",  // 68
        "",  // 69
        "Stow-on-Side",  // 70
        "",  // 71
        "Stow-on-Side Stadium",  // 72
        "",  // 73
        "",  // 74
        "",  // 75
        "Glimwood Tangle",  // 76
        "",  // 77
        "Ballonlea",  // 78
        "",  // 79
        "Ballonlea Stadium",  // 80
        "",  // 81
        "",  // 82
        "",  // 83
        "Route 7",  // 84
        "",  // 85
        "Route 8",  // 86
        "",  // 87
        "Route 8",  // 88
        "Steamdrift Way",  // 89
        "Route 9",  // 90
        "",  // 91
        "Route 9",  // 92
        "Circhester Bay",  // 93
        "Route 9",  // 94
        "Outer Spikemuth",  // 95
        "Circhester",  // 96
        "",  // 97
        "Circhester Stadium",  // 98
        "",  // 99
        "",  // 100
        "",  // 101
        "Spikemuth",  // 102
        "",  // 103
        "Route 9 Tunnel",  // 104
        "",  // 105
        "Route 10",  // 106
        "",  // 107
        "White Hill Station",  // 108
        "",  // 109
        "Wyndon",  // 110
        "",  // 111
        "Wyndon Station",  // 112
        "",  // 113
        "Wyndon Stadium",  // 114
        "Pokémon League HQ",  // 115
        "Wyndon Stadium",  // 116
        "Locker Room",  // 117
        "Wyndon Stadium",  // 118
        "",  // 119
        "Meetup Spot",  // 120
        "Wild Area",  // 121
        "Rolling Fields",  // 122
        "Wild Area",  // 123
        "Dappled Grove",  // 124
        "Wild Area",  // 125
        "Watchtower Ruins",  // 126
        "Wild Area",  // 127
        "East Lake Axewell",  // 128
        "Wild Area",  // 129
        "West Lake Axewell",  // 130
        "Wild Area",  // 131
        "Axew’s Eye",  // 132
        "Wild Area",  // 133
        "South Lake Miloch",  // 134
        "Wild Area",  // 135
        "Giant’s Seat",  // 136
        "Wild Area",  // 137
        "North Lake Miloch",  // 138
        "Wild Area",  // 139
        "Motostoke Riverbank",  // 140
        "Wild Area",  // 141
        "Bridge Field",  // 142
        "Wild Area",  // 143
        "Stony Wilderness",  // 144
        "Wild Area",  // 145
        "Dusty Bowl",  // 146
        "Wild Area",  // 147
        "Giant’s Mirror",  // 148
        "Wild Area",  // 149
        "Hammerlocke Hills",  // 150
        "Wild Area",  // 151
        "Giant’s Cap",  // 152
        "Wild Area",  // 153
        "Lake of Outrage",  // 154
        "Wild Area",  // 155
        "Wild Area Station",  // 156
        "",  // 157
        "Battle Tower",  // 158
        "",  // 159
        "Rose Tower",  // 160
        "",  // 161
        "Pokémon Den",  // 162
        "",  // 163
        "Fields of Honor",  // 164
        "Isle of Armor",  // 165
        "Soothing Wetlands",  // 166
        "Isle of Armor",  // 167
        "Forest of Focus",  // 168
        "Isle of Armor",  // 169
        "Challenge Beach",  // 170
        "Isle of Armor",  // 171
        "Brawlers’ Cave",  // 172
        "Isle of Armor",  // 173
        "Challenge Road",  // 174
        "Isle of Armor",  // 175
        "Courageous Cavern",  // 176
        "Isle of Armor",  // 177
        "Loop Lagoon",  // 178
        "Isle of Armor",  // 179
        "Training Lowlands",  // 180
        "Isle of Armor",  // 181
        "Warm-Up Tunnel",  // 182
        "Isle of Armor",  // 183
        "Potbottom Desert",  // 184
        "Isle of Armor",  // 185
        "Workout Sea",  // 186
        "Isle of Armor",  // 187
        "Stepping-Stone Sea",  // 188
        "Isle of Armor",  // 189
        "Insular Sea",  // 190
        "Isle of Armor",  // 191
        "Honeycalm Sea",  // 192
        "Isle of Armor",  // 193
        "Honeycalm Island",  // 194
        "Isle of Armor",  // 195
        "Master Dojo",  // 196
        "",  // 197
        "Tower of Darkness",  // 198
        "",  // 199
        "Tower of Waters",  // 200
        "",  // 201
        "Armor Station",  // 202
        "",  // 203
        "Slippery Slope",  // 204
        "Crown Tundra",  // 205
        "Freezington",  // 206
        "Crown Tundra",  // 207
        "Frostpoint Field",  // 208
        "Crown Tundra",  // 209
        "Giant’s Bed",  // 210
        "Crown Tundra",  // 211
        "Old Cemetery",  // 212
        "Crown Tundra",  // 213
        "Snowslide Slope",  // 214
        "Crown Tundra",  // 215
        "Tunnel to the Top",  // 216
        "Crown Tundra",  // 217
        "Path to the Peak",  // 218
        "Crown Tundra",  // 219
        "Crown Shrine",  // 220
        "Crown Tundra",  // 221
        "Giant’s Foot",  // 222
        "Crown Tundra",  // 223
        "Roaring-Sea Caves",  // 224
        "Crown Tundra",  // 225
        "Frigid Sea",  // 226
        "Crown Tundra",  // 227
        "Three-Point Pass",  // 228
        "Crown Tundra",  // 229
        "Ballimere Lake",  // 230
        "Crown Tundra",  // 231
        "Lakeside Cave",  // 232
        "Crown Tundra",  // 233
        "Dyna Tree Hill",  // 234
        "Crown Tundra",  // 235
        "Rock Peak Ruins",  // 236
        "",  // 237
        "Iceberg Ruins",  // 238
        "",  // 239
        "Iron Ruins",  // 240
        "",  // 241
        "Split-Decision Ruins",  // 242
        "",  // 243
        "Max Lair",  // 244
        "",  // 245
        "Crown Tundra Station",  // 246
    };

    // Legends: Arceus (PLA=47)
    // Source: PKHeX text_la_00000_en.txt  (156 entries)
    static const char* const PLA_LOC_NAMES[] = {
        "",  // 0
        "",  // 1
        "Mystery Zone",  // 2
        "",  // 3
        "Faraway place",  // 4
        "",  // 5
        "Jubilife Village",  // 6
        "Obsidian Fieldlands",  // 7
        "Crimson Mirelands",  // 8
        "Cobalt Coastlands",  // 9
        "Coronet Highlands",  // 10
        "Alabaster Icelands",  // 11
        "Ancient Retreat",  // 12
        "Aspiration Hill",  // 13
        "Horseshoe Plains",  // 14
        "Deertrack Path",  // 15
        "Deertrack Heights",  // 16
        "Obsidian Falls",  // 17
        "Oreburrow Tunnel",  // 18
        "Nature’s Pantry",  // 19
        "The Heartwood",  // 20
        "Grandtree Arena",  // 21
        "Grueling Grove",  // 22
        "Lake Verity",  // 23
        "Sandgem Flats",  // 24
        "Tidewater Dam",  // 25
        "Floaro Gardens",  // 26
        "Ramanas Island",  // 27
        "Fieldlands Camp",  // 28
        "Heights Camp",  // 29
        "Windswept Run",  // 30
        "Floaro Gardens",  // 31
        "Worn Bridge",  // 32
        "Moss Rock",  // 33
        "Golden Lowlands",  // 34
        "Solaceon Ruins",  // 35
        "Gapejaw Bog",  // 36
        "Sludge Mound",  // 37
        "Scarlet Bog",  // 38
        "Bolderoll Slope",  // 39
        "Diamond Settlement",  // 40
        "Lake Valor",  // 41
        "Cloudpool Ridge",  // 42
        "Shrouded Ruins",  // 43
        "",  // 44
        "Holm of Trials",  // 45
        "Droning Meadow",  // 46
        "Mirelands Camp",  // 47
        "Bogbound Camp",  // 48
        "Crossing Slope",  // 49
        "Ginkgo Landing",  // 50
        "Deadwood Haunt",  // 51
        "Hideaway Bay",  // 52
        "Tombolo Walk",  // 53
        "Veilstone Cape",  // 54
        "Seagrass Haven",  // 55
        "Firespit Island",  // 56
        "Iscan’s Home",  // 57
        "Spring Path",  // 58
        "Lunker’s Lair",  // 59
        "Islespy Shore",  // 60
        "Windbreak Stand",  // 61
        "",  // 62
        "Tidal Passage",  // 63
        "Seaside Hollow",  // 64
        "Beachside Camp",  // 65
        "Coastlands Camp",  // 66
        "Turnback Cave",  // 67
        "Lava Dome Sanctum",  // 68
        "Highlands Camp",  // 69
        "Heavenward Lookout",  // 70
        "Wayward Wood",  // 71
        "Ancient Quarry",  // 72
        "Celestica Trail",  // 73
        "Lonely Spring",  // 74
        "Fabled Spring",  // 75
        "Bolderoll Ravine",  // 76
        "Stonetooth Rows",  // 77
        "",  // 78
        "Primeval Grotto",  // 79
        "Clamberclaw Cliffs",  // 80
        "Celestica Ruins",  // 81
        "Moonview Arena",  // 82
        "Summit Camp",  // 83
        "Cloudcap Pass",  // 84
        "Spear Pillar",  // 85
        "Wayward Cave",  // 86
        "Snowfields Camp",  // 87
        "Whiteout Valley",  // 88
        "Crevasse Passage",  // 89
        "Bonechill Wastes",  // 90
        "",  // 91
        "Avalugg’s Legacy",  // 92
        "Glacier Terrace",  // 93
        "Lake Acuity",  // 94
        "Snowpoint Temple",  // 95
        "Hibernal Cave",  // 96
        "Icebound Falls",  // 97
        "Avalanche Slopes",  // 98
        "Arena’s Approach",  // 99
        "Pearl Settlement",  // 100
        "Heart’s Crag",  // 101
        "Ice Column Chamber",  // 102
        "Icepeak Camp",  // 103
        "Verity Cavern",  // 104
        "Valor Cavern",  // 105
        "Cottonsedge Prairie",  // 106
        "Mountain Camp",  // 107
        "Stone Portal",  // 108
        "Temple of Sinnoh",  // 109
        "Ice Rock",  // 110
        "Acuity Cavern",  // 111
        "Icepeak Cavern",  // 112
        "Secret Hollow",  // 113
        "Galaxy Hall",  // 114
        "General Store",  // 115
        "Candy Stand",  // 116
        "Craftworks",  // 117
        "Ginkgo Guild Cart",  // 118
        "Trading Post",  // 119
        "Pastures",  // 120
        "Clothier",  // 121
        "Hairdresser",  // 122
        "Photography Studio",  // 123
        "Farm",  // 124
        "Training Grounds",  // 125
        "Folk Shrine",  // 126
        "Your Quarters",  // 127
        "Castaway Shore",  // 128
        "Sand’s Reach",  // 129
        "Sonorous Path",  // 130
        "Sacred Plaza",  // 131
        "Front Gate",  // 132
        "Seaside Gate",  // 133
        "Canala Avenue",  // 134
        "Floaro Main Street",  // 135
        "Prelude Beach",  // 136
        "Practice Field",  // 137
        "???",  // 138
        "Brava Arena",  // 139
        "Molten Arena",  // 140
        "Icepeak Arena",  // 141
        "Snowfall Hot Spring",  // 142
        "First Floor",  // 143
        "Second Floor",  // 144
        "Third Floor",  // 145
        "Basement",  // 146
        "Ursa’s Ring",  // 147
        "Diamond Heath",  // 148
        "Aipom Hill",  // 149
        "Bathers’ Lagoon",  // 150
        "Tranquility Cove",  // 151
        "Galaxy Hall",  // 152
        "Front Gate",  // 153
        "Farm",  // 154
        "Training Grounds",  // 155
    };

    // Brilliant Diamond / Shining Pearl (BD=48, SP=49)
    // Source: PKHeX text_bdsp_00000_en.txt  (658 entries)
    static const char* const BDSP_LOC_NAMES[] = {
        "Jubilife City",  // 0
        "Jubilife City",  // 1
        "Jubilife City",  // 2
        "Jubilife City",  // 3
        "Jubilife City",  // 4
        "Jubilife City",  // 5
        "Jubilife City",  // 6
        "Jubilife City",  // 7
        "Jubilife City",  // 8
        "Jubilife City",  // 9
        "Jubilife City",  // 10
        "Jubilife City",  // 11
        "Jubilife City",  // 12
        "Jubilife City",  // 13
        "Jubilife City",  // 14
        "Jubilife City",  // 15
        "Jubilife City",  // 16
        "Jubilife City",  // 17
        "Jubilife City",  // 18
        "Jubilife City",  // 19
        "Jubilife City",  // 20
        "Jubilife City",  // 21
        "Jubilife City",  // 22
        "Jubilife City",  // 23
        "Canalave City",  // 24
        "Canalave City",  // 25
        "Canalave Gym",  // 26
        "Canalave City",  // 27
        "Canalave City",  // 28
        "Canalave City",  // 29
        "Canalave City",  // 30
        "Canalave City",  // 31
        "Canalave City",  // 32
        "Canalave City",  // 33
        "Canalave City",  // 34
        "Canalave City",  // 35
        "Canalave City",  // 36
        "Canalave City",  // 37
        "Oreburgh City",  // 38
        "Oreburgh City",  // 39
        "Oreburgh Gym",  // 40
        "Oreburgh City",  // 41
        "Oreburgh City",  // 42
        "Oreburgh City",  // 43
        "Oreburgh City",  // 44
        "Oreburgh City",  // 45
        "Oreburgh City",  // 46
        "Oreburgh City",  // 47
        "Oreburgh City",  // 48
        "Oreburgh City",  // 49
        "Oreburgh City",  // 50
        "Oreburgh City",  // 51
        "Oreburgh City",  // 52
        "Oreburgh City",  // 53
        "Eterna City",  // 54
        "Eterna City",  // 55
        "Eterna Gym",  // 56
        "Eterna Gym",  // 57
        "Eterna City",  // 58
        "Eterna City",  // 59
        "Eterna City",  // 60
        "Eterna City",  // 61
        "Eterna City",  // 62
        "Eterna City",  // 63
        "Eterna City",  // 64
        "Eterna City",  // 65
        "Eterna City",  // 66
        "Eterna City",  // 67
        "Eterna City",  // 68
        "Eterna City",  // 69
        "Eterna City",  // 70
        "Eterna City",  // 71
        "Eterna City",  // 72
        "Eterna City",  // 73
        "Hearthome City",  // 74
        "Hearthome City",  // 75
        "Hearthome Gym",  // 76
        "Hearthome Gym",  // 77
        "Hearthome Gym",  // 78
        "Hearthome Gym",  // 79
        "Hearthome Gym",  // 80
        "Hearthome Gym",  // 81
        "Hearthome Gym",  // 82
        "Hearthome Gym",  // 83
        "Hearthome Gym",  // 84
        "Hearthome Gym",  // 85
        "Hearthome Gym",  // 86
        "Hearthome Gym",  // 87
        "Hearthome Gym",  // 88
        "Hearthome City",  // 89
        "Hearthome City",  // 90
        "Hearthome City",  // 91
        "Hearthome City",  // 92
        "Hearthome City",  // 93
        "Hearthome City",  // 94
        "Hearthome City",  // 95
        "Hearthome City",  // 96
        "Hearthome City",  // 97
        "Hearthome City",  // 98
        "Hearthome City",  // 99
        "Hearthome City",  // 100
        "Hearthome City",  // 101
        "Hearthome City",  // 102
        "Hearthome City",  // 103
        "Hearthome City",  // 104
        "Hearthome City",  // 105
        "Hearthome City",  // 106
        "Hearthome City",  // 107
        "Hearthome City",  // 108
        "Hearthome City",  // 109
        "Pastoria City",  // 110
        "Pastoria City",  // 111
        "Pastoria Gym",  // 112
        "Pastoria City",  // 113
        "Pastoria City",  // 114
        "Pastoria City",  // 115
        "Pastoria City",  // 116
        "Pastoria City",  // 117
        "Pastoria City",  // 118
        "Pastoria City",  // 119
        "Pastoria City",  // 120
        "Pastoria City",  // 121
        "Pastoria City",  // 122
        "Veilstone City",  // 123
        "Veilstone Gym",  // 124
        "Veilstone City",  // 125
        "Veilstone City",  // 126
        "Veilstone City",  // 127
        "Veilstone City",  // 128
        "Veilstone City",  // 129
        "Veilstone City",  // 130
        "Veilstone City",  // 131
        "Veilstone City",  // 132
        "Veilstone City",  // 133
        "Veilstone City",  // 134
        "Veilstone City",  // 135
        "Veilstone City",  // 136
        "Veilstone City",  // 137
        "Veilstone City",  // 138
        "Veilstone City",  // 139
        "Veilstone City",  // 140
        "Veilstone City",  // 141
        "Sunyshore City",  // 142
        "Sunyshore City",  // 143
        "Sunyshore Gym",  // 144
        "Sunyshore Gym",  // 145
        "Sunyshore Gym",  // 146
        "Sunyshore City",  // 147
        "Sunyshore City",  // 148
        "Sunyshore City",  // 149
        "Sunyshore City",  // 150
        "Sunyshore City",  // 151
        "Sunyshore City",  // 152
        "Sunyshore City",  // 153
        "Sunyshore City",  // 154
        "Sunyshore City",  // 155
        "Sunyshore City",  // 156
        "Sunyshore City",  // 157
        "Sunyshore City",  // 158
        "Snowpoint City",  // 159
        "Snowpoint City",  // 160
        "Snowpoint Gym",  // 161
        "Snowpoint City",  // 162
        "Snowpoint City",  // 163
        "Snowpoint City",  // 164
        "Snowpoint City",  // 165
        "Snowpoint City",  // 166
        "Pokémon League",  // 167
        "Pokémon League",  // 168
        "Pokémon League",  // 169
        "Pokémon League",  // 170
        "Pokémon League",  // 171
        "Pokémon League",  // 172
        "Pokémon League",  // 173
        "Pokémon League",  // 174
        "Pokémon League",  // 175
        "Pokémon League",  // 176
        "Pokémon League",  // 177
        "Pokémon League",  // 178
        "Pokémon League",  // 179
        "Pokémon League",  // 180
        "Pokémon League",  // 181
        "Pokémon League",  // 182
        "Pokémon League",  // 183
        "Pokémon League",  // 184
        "Pokémon League",  // 185
        "Fight Area",  // 186
        "Fight Area",  // 187
        "Fight Area",  // 188
        "Fight Area",  // 189
        "Fight Area",  // 190
        "Fight Area",  // 191
        "Fight Area",  // 192
        "Fight Area",  // 193
        "Fight Area",  // 194
        "Oreburgh Mine",  // 195
        "Oreburgh Mine",  // 196
        "Valley Windworks",  // 197
        "Valley Windworks",  // 198
        "Eterna Forest",  // 199
        "Eterna Forest",  // 200
        "Fuego Ironworks",  // 201
        "Fuego Ironworks",  // 202
        "Mount Coronet",  // 203
        "Mount Coronet",  // 204
        "Mount Coronet",  // 205
        "Mount Coronet",  // 206
        "Mount Coronet",  // 207
        "Mount Coronet",  // 208
        "Mount Coronet",  // 209
        "Mount Coronet",  // 210
        "Mount Coronet",  // 211
        "Mount Coronet",  // 212
        "Mount Coronet",  // 213
        "Mount Coronet",  // 214
        "Mount Coronet",  // 215
        "Spear Pillar",  // 216
        "Spear Pillar",  // 217
        "Hall of Origin",  // 218
        "Great Marsh",  // 219
        "Great Marsh",  // 220
        "Great Marsh",  // 221
        "Great Marsh",  // 222
        "Great Marsh",  // 223
        "Great Marsh",  // 224
        "Solaceon Ruins",  // 225
        "Solaceon Ruins",  // 226
        "Solaceon Ruins",  // 227
        "Solaceon Ruins",  // 228
        "Solaceon Ruins",  // 229
        "Solaceon Ruins",  // 230
        "Solaceon Ruins",  // 231
        "Solaceon Ruins",  // 232
        "Solaceon Ruins",  // 233
        "Solaceon Ruins",  // 234
        "Solaceon Ruins",  // 235
        "Solaceon Ruins",  // 236
        "Solaceon Ruins",  // 237
        "Solaceon Ruins",  // 238
        "Solaceon Ruins",  // 239
        "Solaceon Ruins",  // 240
        "Solaceon Ruins",  // 241
        "Solaceon Ruins",  // 242
        "Solaceon Ruins",  // 243
        "Victory Road",  // 244
        "Victory Road",  // 245
        "Victory Road",  // 246
        "Victory Road",  // 247
        "Victory Road",  // 248
        "Victory Road",  // 249
        "Ramanas Park",  // 250
        "Amity Square",  // 251
        "Ravaged Path",  // 252
        "Floaroma Meadow",  // 253
        "Floaroma Meadow",  // 254
        "Oreburgh Gate",  // 255
        "Oreburgh Gate",  // 256
        "Fullmoon Island",  // 257
        "Fullmoon Island",  // 258
        "Stark Mountain",  // 259
        "Stark Mountain",  // 260
        "Stark Mountain",  // 261
        "Stark Mountain",  // 262
        "Sendoff Spring",  // 263
        "Turnback Cave",  // 264
        "Turnback Cave",  // 265
        "Turnback Cave",  // 266
        "Turnback Cave",  // 267
        "Turnback Cave",  // 268
        "Turnback Cave",  // 269
        "Turnback Cave",  // 270
        "Turnback Cave",  // 271
        "Turnback Cave",  // 272
        "Turnback Cave",  // 273
        "Turnback Cave",  // 274
        "Turnback Cave",  // 275
        "Turnback Cave",  // 276
        "Turnback Cave",  // 277
        "Turnback Cave",  // 278
        "Turnback Cave",  // 279
        "Turnback Cave",  // 280
        "Turnback Cave",  // 281
        "Turnback Cave",  // 282
        "Turnback Cave",  // 283
        "Turnback Cave",  // 284
        "Flower Paradise",  // 285
        "Snowpoint Temple",  // 286
        "Snowpoint Temple",  // 287
        "Snowpoint Temple",  // 288
        "Snowpoint Temple",  // 289
        "Snowpoint Temple",  // 290
        "Snowpoint Temple",  // 291
        "Wayward Cave",  // 292
        "Wayward Cave",  // 293
        "Ruin Maniac Cave",  // 294
        "Ruin Maniac Cave",  // 295
        "Maniac Tunnel",  // 296
        "Trophy Garden",  // 297
        "Iron Island",  // 298
        "Iron Island",  // 299
        "Iron Island",  // 300
        "Iron Island",  // 301
        "Iron Island",  // 302
        "Iron Island",  // 303
        "Iron Island",  // 304
        "Iron Island",  // 305
        "Old Chateau",  // 306
        "Old Chateau",  // 307
        "Old Chateau",  // 308
        "Old Chateau",  // 309
        "Old Chateau",  // 310
        "Old Chateau",  // 311
        "Old Chateau",  // 312
        "Old Chateau",  // 313
        "Old Chateau",  // 314
        "Galactic HQ",  // 315
        "Galactic HQ",  // 316
        "Galactic HQ",  // 317
        "Galactic HQ",  // 318
        "Galactic HQ",  // 319
        "Galactic HQ",  // 320
        "Galactic HQ",  // 321
        "Galactic HQ",  // 322
        "Lake Verity",  // 323
        "Lake Verity",  // 324
        "Lake Verity (Verity Cavern)",  // 325
        "Lake Valor",  // 326
        "Lake Valor",  // 327
        "Lake Valor (Valor Cavern)",  // 328
        "Lake Acuity",  // 329
        "Lake Acuity",  // 330
        "Lake Acuity (Acuity Cavern)",  // 331
        "Newmoon Island",  // 332
        "Newmoon Island",  // 333
        "Battle Park",  // 334
        "Battle Park",  // 335
        "Battle Park",  // 336
        "Battle Park",  // 337
        "Battle Park",  // 338
        "Battle Tower",  // 339
        "Battle Tower",  // 340
        "Battle Tower",  // 341
        "Battle Tower",  // 342
        "Battle Tower",  // 343
        "Battle Tower",  // 344
        "Mystery Zone",  // 345
        "Verity Lakefront",  // 346
        "Valor Lakefront",  // 347
        "Valor Lakefront",  // 348
        "Valor Lakefront",  // 349
        "Valor Lakefront",  // 350
        "Acuity Lakefront",  // 351
        "Spring Path",  // 352
        "Mystery Zone",  // 353
        "Route 201",  // 354
        "Route 202",  // 355
        "Route 203",  // 356
        "Route 204",  // 357
        "Route 204",  // 358
        "Route 205",  // 359
        "Route 205",  // 360
        "Route 205",  // 361
        "Route 206",  // 362
        "Route 206",  // 363
        "Route 207",  // 364
        "Route 208",  // 365
        "Route 208",  // 366
        "Route 209",  // 367
        "Route 209",  // 368
        "Route 209",  // 369
        "Route 209",  // 370
        "Route 209",  // 371
        "Route 209",  // 372
        "Route 210",  // 373
        "Route 210",  // 374
        "Route 210",  // 375
        "Route 210",  // 376
        "Route 211",  // 377
        "Route 211",  // 378
        "Route 212",  // 379
        "Route 212",  // 380
        "Route 212",  // 381
        "Route 212",  // 382
        "Route 212",  // 383
        "Route 212",  // 384
        "Route 213",  // 385
        "Route 213",  // 386
        "Route 213",  // 387
        "Route 213",  // 388
        "Route 213",  // 389
        "Route 213",  // 390
        "Route 213",  // 391
        "Route 214",  // 392
        "Route 214",  // 393
        "Route 215",  // 394
        "Route 216",  // 395
        "Route 216",  // 396
        "Route 217",  // 397
        "Route 217",  // 398
        "Route 217",  // 399
        "Route 218",  // 400
        "Route 218",  // 401
        "Route 218",  // 402
        "Route 219",  // 403
        "Route 221",  // 404
        "Route 221",  // 405
        "Route 221",  // 406
        "Route 222",  // 407
        "Route 222",  // 408
        "Route 222",  // 409
        "Route 222",  // 410
        "Route 224",  // 411
        "Route 225",  // 412
        "Route 225",  // 413
        "Route 227",  // 414
        "Route 227",  // 415
        "Route 228",  // 416
        "Route 228",  // 417
        "Route 228",  // 418
        "Route 228",  // 419
        "Route 229",  // 420
        "Mystery Zone",  // 421
        "Twinleaf Town",  // 422
        "Twinleaf Town",  // 423
        "Twinleaf Town",  // 424
        "Twinleaf Town",  // 425
        "Twinleaf Town",  // 426
        "Twinleaf Town",  // 427
        "Twinleaf Town",  // 428
        "Sandgem Town",  // 429
        "Sandgem Town",  // 430
        "Sandgem Town",  // 431
        "Sandgem Town",  // 432
        "Sandgem Town",  // 433
        "Sandgem Town",  // 434
        "Sandgem Town",  // 435
        "Sandgem Town",  // 436
        "Sandgem Town",  // 437
        "Floaroma Town",  // 438
        "Floaroma Town",  // 439
        "Floaroma Town",  // 440
        "Floaroma Town",  // 441
        "Floaroma Town",  // 442
        "Floaroma Town",  // 443
        "Floaroma Town",  // 444
        "Floaroma Town",  // 445
        "Solaceon Town",  // 446
        "Solaceon Town",  // 447
        "Solaceon Town",  // 448
        "Solaceon Town",  // 449
        "Solaceon Town",  // 450
        "Solaceon Town",  // 451
        "Solaceon Town",  // 452
        "Solaceon Town",  // 453
        "Solaceon Town",  // 454
        "Solaceon Town",  // 455
        "Celestic Town",  // 456
        "Celestic Town",  // 457
        "Celestic Town",  // 458
        "Celestic Town",  // 459
        "Celestic Town",  // 460
        "Celestic Town",  // 461
        "Celestic Town",  // 462
        "Celestic Town",  // 463
        "Celestic Town",  // 464
        "Survival Area",  // 465
        "Survival Area",  // 466
        "Survival Area",  // 467
        "Survival Area",  // 468
        "Survival Area",  // 469
        "Survival Area",  // 470
        "Survival Area",  // 471
        "Survival Area",  // 472
        "Resort Area",  // 473
        "Resort Area",  // 474
        "Resort Area",  // 475
        "Resort Area",  // 476
        "Resort Area",  // 477
        "Resort Area",  // 478
        "Resort Area",  // 479
        "Resort Area",  // 480
        "Resort Area",  // 481
        "Resort Area",  // 482
        "Mystery Zone",  // 483
        "Mystery Zone",  // 484
        "Route 220",  // 485
        "Route 223",  // 486
        "Route 226",  // 487
        "Route 226",  // 488
        "Route 230",  // 489
        "Seabreak Path",  // 490
        "Mystery Zone",  // 491
        "Mystery Zone",  // 492
        "Mystery Zone",  // 493
        "Eterna City",  // 494
        "Ramanas Park",  // 495
        "Ramanas Park (Discovery Room)",  // 496
        "Ramanas Park (Kanto Room)",  // 497
        "Ramanas Park (Johto Room)",  // 498
        "Ramanas Park (Soul Room)",  // 499
        "Ramanas Park (Tectonic Room)",  // 500
        "Ramanas Park (Oceanic Room)",  // 501
        "Ramanas Park (Stratospheric Room)",  // 502
        "Ramanas Park (Rainbow Room)",  // 503
        "Ramanas Park (Squall Room)",  // 504
        "Ramanas Park (Genome Room)",  // 505
        "Ramanas Park (Pure Space)",  // 506
        "Ramanas Park (Strange Space)",  // 507
        "Grand Underground",  // 508
        "Grand Underground",  // 509
        "Grand Underground",  // 510
        "Grand Underground",  // 511
        "Grand Underground",  // 512
        "Grand Underground",  // 513
        "Grand Underground",  // 514
        "Grand Underground",  // 515
        "Grand Underground",  // 516
        "Grand Underground",  // 517
        "Grand Underground",  // 518
        "Grand Underground",  // 519
        "Grand Underground",  // 520
        "Grand Underground",  // 521
        "Grand Underground",  // 522
        "Grand Underground",  // 523
        "Grand Underground",  // 524
        "Grand Underground",  // 525
        "Grand Underground",  // 526
        "Grand Underground",  // 527
        "Grand Underground",  // 528
        "Grand Underground",  // 529
        "Grand Underground",  // 530
        "Grand Underground",  // 531
        "Grand Underground",  // 532
        "Grand Underground",  // 533
        "Grand Underground",  // 534
        "Grand Underground",  // 535
        "Grand Underground",  // 536
        "Grand Underground",  // 537
        "Grand Underground",  // 538
        "Grand Underground",  // 539
        "Grand Underground",  // 540
        "Grand Underground",  // 541
        "Grand Underground",  // 542
        "Grand Underground (Spacious Cave)",  // 543
        "Grand Underground (Grassland Cave)",  // 544
        "Grand Underground (Riverbank Cave)",  // 545
        "Grand Underground (Spacious Cave)",  // 546
        "Grand Underground (Spacious Cave)",  // 547
        "Grand Underground (Swampy Cave)",  // 548
        "Grand Underground (Grassland Cave)",  // 549
        "Grand Underground (Fountainspring Cave)",  // 550
        "Grand Underground (Spacious Cave)",  // 551
        "Grand Underground (Fountainspring Cave)",  // 552
        "Grand Underground (Fountainspring Cave)",  // 553
        "Grand Underground (Spacious Cave)",  // 554
        "Grand Underground (Spacious Cave)",  // 555
        "Grand Underground (Rocky Cave)",  // 556
        "Grand Underground (Volcanic Cave)",  // 557
        "Grand Underground (Spacious Cave)",  // 558
        "Grand Underground (Rocky Cave)",  // 559
        "Grand Underground (Volcanic Cave)",  // 560
        "Grand Underground (Dazzling Cave)",  // 561
        "Grand Underground (Sandsear Cave)",  // 562
        "Grand Underground (Spacious Cave)",  // 563
        "Grand Underground (Spacious Cave)",  // 564
        "Grand Underground (Rocky Cave)",  // 565
        "Grand Underground (Spacious Cave)",  // 566
        "Grand Underground (Grassland Cave)",  // 567
        "Grand Underground (Riverbank Cave)",  // 568
        "Grand Underground (Spacious Cave)",  // 569
        "Grand Underground (Grassland Cave)",  // 570
        "Grand Underground (Fountainspring Cave)",  // 571
        "Grand Underground (Swampy Cave)",  // 572
        "Grand Underground (Spacious Cave)",  // 573
        "Grand Underground (Spacious Cave)",  // 574
        "Grand Underground (Spacious Cave)",  // 575
        "Grand Underground (Swampy Cave)",  // 576
        "Grand Underground (Riverbank Cave)",  // 577
        "Grand Underground (Icy Cave)",  // 578
        "Grand Underground (Dazzling Cave)",  // 579
        "Grand Underground (Dazzling Cave)",  // 580
        "Grand Underground (Icy Cave)",  // 581
        "Grand Underground (Icy Cave)",  // 582
        "Grand Underground (Icy Cave)",  // 583
        "Grand Underground (Spacious Cave)",  // 584
        "Grand Underground (Spacious Cave)",  // 585
        "Grand Underground (Whiteout Cave)",  // 586
        "Grand Underground (Whiteout Cave)",  // 587
        "Grand Underground (Whiteout Cave)",  // 588
        "Grand Underground (Whiteout Cave)",  // 589
        "Grand Underground (Swampy Cave)",  // 590
        "Grand Underground (Fountainspring Cave)",  // 591
        "Grand Underground (Spacious Cave)",  // 592
        "Grand Underground (Swampy Cave)",  // 593
        "Grand Underground (Spacious Cave)",  // 594
        "Grand Underground (Fountainspring Cave)",  // 595
        "Grand Underground (Rocky Cave)",  // 596
        "Grand Underground (Swampy Cave)",  // 597
        "Grand Underground (Spacious Cave)",  // 598
        "Grand Underground (Sandsear Cave)",  // 599
        "Grand Underground (Volcanic Cave)",  // 600
        "Grand Underground (Dazzling Cave)",  // 601
        "Grand Underground (Volcanic Cave)",  // 602
        "Grand Underground (Rocky Cave)",  // 603
        "Grand Underground (Fountainspring Cave)",  // 604
        "Grand Underground (Grassland Cave)",  // 605
        "Grand Underground (Spacious Cave)",  // 606
        "Grand Underground (Swampy Cave)",  // 607
        "Grand Underground (Rocky Cave)",  // 608
        "Grand Underground (Sandsear Cave)",  // 609
        "Grand Underground (Volcanic Cave)",  // 610
        "Grand Underground (Still-Water Cavern)",  // 611
        "Grand Underground (Big Bluff Cavern)",  // 612
        "Grand Underground (Sunlit Cavern)",  // 613
        "Grand Underground (Stargleam Cavern)",  // 614
        "Grand Underground (Glacial Cavern)",  // 615
        "Grand Underground (Bogsunk Cavern)",  // 616
        "Grand Underground (Typhlo Cavern)",  // 617
        "Hall of Origin",  // 618
        "Ramanas Park (Distortion Room)",  // 619
        "Grand Underground (Secret Base)",  // 620
        "Grand Underground (Secret Base)",  // 621
        "Grand Underground (Secret Base)",  // 622
        "Grand Underground (Secret Base)",  // 623
        "Ramanas Park (Distortion Room)",  // 624
        "Ramanas Park",  // 625
        "Jubilife City",  // 626
        "Grand Underground (Secret Base)",  // 627
        "Grand Underground (Secret Base)",  // 628
        "Grand Underground (Secret Base)",  // 629
        "Grand Underground (Secret Base)",  // 630
        "Grand Underground (Secret Base)",  // 631
        "Grand Underground (Secret Base)",  // 632
        "Grand Underground (Secret Base)",  // 633
        "Grand Underground (Secret Base)",  // 634
        "Grand Underground (Secret Base)",  // 635
        "Grand Underground (Secret Base)",  // 636
        "Grand Underground (Secret Base)",  // 637
        "Grand Underground (Secret Base)",  // 638
        "Grand Underground (Secret Base)",  // 639
        "Grand Underground (Secret Base)",  // 640
        "Grand Underground (Secret Base)",  // 641
        "Grand Underground (Secret Base)",  // 642
        "Grand Underground (Secret Base)",  // 643
        "Grand Underground (Secret Base)",  // 644
        "Grand Underground (Secret Base)",  // 645
        "Grand Underground (Secret Base)",  // 646
        "Grand Underground (Secret Base)",  // 647
        "Ramanas Park (Discovery Room)",  // 648
        "Ramanas Park (Kanto Room)",  // 649
        "Ramanas Park (Johto Room)",  // 650
        "Ramanas Park (Soul Room)",  // 651
        "Ramanas Park (Tectonic Room)",  // 652
        "Ramanas Park (Oceanic Room)",  // 653
        "Ramanas Park (Stratospheric Room)",  // 654
        "Ramanas Park (Rainbow Room)",  // 655
        "Ramanas Park (Squall Room)",  // 656
        "Ramanas Park (Genome Room)",  // 657
    };

    // Scarlet / Violet (SL=50, VL=51)
    // Source: PKHeX text_sv_00000_en.txt  (201 entries)
    static const char* const SV_LOC_NAMES[] = {
        "",  // 0
        "",  // 1
        "Mystery Zone",  // 2
        "",  // 3
        "Faraway place",  // 4
        "",  // 5
        "South Province (Area One)",  // 6
        "",  // 7
        "Mesagoza",  // 8
        "",  // 9
        "Pokémon League",  // 10
        "",  // 11
        "South Province (Area Two)",  // 12
        "",  // 13
        "South Province (Area Four)",  // 14
        "",  // 15
        "South Province (Area Six)",  // 16
        "",  // 17
        "South Province (Area Five)",  // 18
        "",  // 19
        "South Province (Area Three)",  // 20
        "",  // 21
        "West Province (Area One)",  // 22
        "",  // 23
        "Asado Desert",  // 24
        "",  // 25
        "West Province (Area Two)",  // 26
        "",  // 27
        "West Province (Area Three)",  // 28
        "",  // 29
        "Tagtree Thicket",  // 30
        "",  // 31
        "East Province (Area Three)",  // 32
        "",  // 33
        "East Province (Area One)",  // 34
        "",  // 35
        "East Province (Area Two)",  // 36
        "",  // 37
        "Glaseado Mountain",  // 38
        "",  // 39
        "Casseroya Lake",  // 40
        "",  // 41
        "Glaseado Mountain",  // 42
        "",  // 43
        "North Province (Area Three)",  // 44
        "",  // 45
        "North Province (Area One)",  // 46
        "",  // 47
        "North Province (Area Two)",  // 48
        "",  // 49
        "Great Crater of Paldea",  // 50
        "",  // 51
        "Zero Gate",  // 52
        "",  // 53
        "Zero Gate",  // 54
        "",  // 55
        "South Paldean Sea",  // 56
        "",  // 57
        "West Paldean Sea",  // 58
        "",  // 59
        "East Paldean Sea",  // 60
        "",  // 61
        "North Paldean Sea",  // 62
        "",  // 63
        "Inlet Grotto",  // 64
        "",  // 65
        "South Province (Area Six)",  // 66
        "Alfornada Cavern",  // 67
        "Glaseado Mountain",  // 68
        "Dalizapa Passage",  // 69
        "Poco Path",  // 70
        "",  // 71
        "Mesagoza",  // 72
        "",  // 73
        "Mesagoza",  // 74
        "",  // 75
        "Cascarrafa",  // 76
        "",  // 77
        "Levincia",  // 78
        "",  // 79
        "Cabo Poco",  // 80
        "",  // 81
        "Los Platos",  // 82
        "",  // 83
        "Cortondo",  // 84
        "",  // 85
        "Artazon",  // 86
        "",  // 87
        "Porto Marinada",  // 88
        "",  // 89
        "Medali",  // 90
        "",  // 91
        "Zapapico",  // 92
        "",  // 93
        "Montenevera",  // 94
        "",  // 95
        "Alfornada",  // 96
        "",  // 97
        "North Province (Area Two)",  // 98
        "Caph Squad’s Base",  // 99
        "West Province (Area One)",  // 100
        "Segin Squad’s Base",  // 101
        "North Province (Area Three)",  // 102
        "Ruchbah Squad’s Base",  // 103
        "East Province (Area One)",  // 104
        "Schedar Squad’s Base",  // 105
        "Tagtree Thicket",  // 106
        "Navi Squad’s Base",  // 107
        "Casseroya Lake",  // 108
        "Socarrat Trail",  // 109
        "Area Zero",  // 110
        "Research Station No. 1",  // 111
        "Area Zero",  // 112
        "Research Station No. 2",  // 113
        "Area Zero",  // 114
        "Research Station No. 3",  // 115
        "Area Zero",  // 116
        "Research Station No. 4",  // 117
        "Zero Lab",  // 118
        "",  // 119
        "Zero Lab",  // 120
        "",  // 121
        "Zero Lab",  // 122
        "",  // 123
        "Area Zero",  // 124
        "",  // 125
        "Area Zero",  // 126
        "",  // 127
        "Area Zero",  // 128
        "",  // 129
        "Naranja Academy",  // 130
        "Uva Academy",  // 131
        "Kitakami Road",  // 132
        "",  // 133
        "Mossui Town",  // 134
        "",  // 135
        "Apple Hills",  // 136
        "",  // 137
        "Loyalty Plaza",  // 138
        "",  // 139
        "Reveler’s Road",  // 140
        "",  // 141
        "Kitakami Hall",  // 142
        "",  // 143
        "Oni Mountain",  // 144
        "",  // 145
        "Dreaded Den",  // 146
        "Oni Mountain",  // 147
        "Oni’s Maw",  // 148
        "Oni Mountain",  // 149
        "Oni Mountain",  // 150
        "",  // 151
        "Crystal Pool",  // 152
        "Oni Mountain Summit",  // 153
        "Crystal Pool",  // 154
        "Oni Mountain Summit",  // 155
        "Wistful Fields",  // 156
        "",  // 157
        "Mossfell Confluence",  // 158
        "",  // 159
        "Fellhorn Gorge",  // 160
        "",  // 161
        "Paradise Barrens",  // 162
        "",  // 163
        "Kitakami Wilds",  // 164
        "",  // 165
        "Timeless Woods",  // 166
        "Kitakami Wilds",  // 167
        "Infernal Pass",  // 168
        "Oni Mountain",  // 169
        "Chilling Waterhead",  // 170
        "",  // 171
        "Blueberry Academy",  // 172
        "",  // 173
        "Savanna Biome",  // 174
        "",  // 175
        "Coastal Biome",  // 176
        "",  // 177
        "Canyon Biome",  // 178
        "",  // 179
        "Polar Biome",  // 180
        "",  // 181
        "Central Plaza",  // 182
        "",  // 183
        "Savanna Plaza",  // 184
        "",  // 185
        "Coastal Plaza",  // 186
        "",  // 187
        "Canyon Plaza",  // 188
        "",  // 189
        "Polar Plaza",  // 190
        "",  // 191
        "Chargestone Cavern",  // 192
        "",  // 193
        "Torchlit Labyrinth",  // 194
        "",  // 195
        "Area Zero Underdepths",  // 196
        "",  // 197
        "Area Zero Underdepths",  // 198
        "",  // 199
        "Terarium",  // 200
    };

    // Legends: Z-A (ZA=52)
    // Source: PKHeX text_za_00000_en.txt  (284 entries)
    static const char* const ZA_LOC_NAMES[] = {
        "",  // 0
        "",  // 1
        "Mystery Zone",  // 2
        "",  // 3
        "Faraway place",  // 4
        "",  // 5
        "Vert District",  // 6
        "Bleu District",  // 7
        "Magenta District",  // 8
        "Rouge District",  // 9
        "Jaune District",  // 10
        "Centrico Plaza",  // 11
        "Vernal Avenue",  // 12
        "Estival Avenue",  // 13
        "Autumnal Avenue",  // 14
        "Hibernal Avenue",  // 15
        "Saison Canal",  // 16
        "Vert Street",  // 17
        "Vert Street",  // 18
        "South Boulevard",  // 19
        "South Boulevard",  // 20
        "Vert Sector 1",  // 21
        "Vert Sector 3",  // 22
        "Coulant Waterway",  // 23
        "Vert Sector 6",  // 24
        "Vert Sector 7",  // 25
        "Station Front",  // 26
        "Vert Sector 2",  // 27
        "Vert Sector 4",  // 28
        "Vert Sector 5",  // 29
        "Vert Sector 8",  // 30
        "Vert Sector 9",  // 31
        "Vert Plaza",  // 32
        "Bleu Street",  // 33
        "Bleu Street",  // 34
        "South Boulevard",  // 35
        "South Boulevard",  // 36
        "Bleu Sector 1",  // 37
        "Bleu Sector 3",  // 38
        "Aymlis Park",  // 39
        "Bleu Sector 5",  // 40
        "Bleu Sector 7",  // 41
        "Bleu Sector 2",  // 42
        "Bleu Sector 4",  // 43
        "Espace Vide",  // 44
        "Bleu Sector 6",  // 45
        "Bleu Sector 8",  // 46
        "Bleu Sector 9",  // 47
        "Bleu Sector 10",  // 48
        "Bleu Plaza",  // 49
        "Magenta Street",  // 50
        "Magenta Street",  // 51
        "South Boulevard",  // 52
        "North Boulevard",  // 53
        "Magenta Sector 1",  // 54
        "Magenta Sector 3",  // 55
        "Magenta Sector 5",  // 56
        "Magenta Sector 6",  // 57
        "Electrical Substation",  // 58
        "Magenta Sector 2",  // 59
        "Magenta Sector 4",  // 60
        "Magenta Sector 7",  // 61
        "Quasartico Inc.",  // 62
        "Magenta Sector 8",  // 63
        "Magenta Sector 9",  // 64
        "Magenta Plaza",  // 65
        "Rouge Street",  // 66
        "Rouge Street",  // 67
        "North Boulevard",  // 68
        "North Boulevard",  // 69
        "Rouge Sector 1",  // 70
        "Rouge Sector 3",  // 71
        "Rouge Sector 4",  // 72
        "Rouge Sector 5",  // 73
        "Rouge Sector 7",  // 74
        "Rouge Sector 2",  // 75
        "Académie Étoile",  // 76
        "Rouge Sector 6",  // 77
        "Dormez Bien Cemetery",  // 78
        "Rouge Sector 8",  // 79
        "Rouge Plaza",  // 80
        "Jaune Street",  // 81
        "Jaune Street",  // 82
        "North Boulevard",  // 83
        "North Boulevard",  // 84
        "Jaune Sector 1",  // 85
        "Jaune Sector 3",  // 86
        "Jaune Sector 4",  // 87
        "Jaune Sector 5",  // 88
        "Jaune Sector 7",  // 89
        "Jaune Sector 8",  // 90
        "Jaune Sector 2",  // 91
        "Saison Canalside",  // 92
        "Jaune Sector 6",  // 93
        "Jaune Sector 9",  // 94
        "Jaune Sector 10",  // 95
        "Jaune Sector 11",  // 96
        "Jaune Sector 12",  // 97
        "Jaune Plaza",  // 98
        "Promenade du Vent",  // 99
        "Lumiose Museum",  // 100
        "Vert Pokémon Center",  // 101
        "Hotel Z",  // 102
        "Pokémon Research Lab",  // 103
        "Prism Tower",  // 104
        "Looker Bureau",  // 105
        "Quasartico Inc.",  // 106
        "Racine Construction",  // 107
        "Vert Plaza",  // 108
        "Gare de Lumiose",  // 109
        "Bleu Plaza",  // 110
        "Rust Syndicate Office",  // 111
        "Bleu Pokémon Center",  // 112
        "Vernal Pokémon Center",  // 113
        "Magenta Plaza",  // 114
        "Lysandre Café",  // 115
        "Magenta Pokémon Center",  // 116
        "Magenta Plaza Pokémon Center",  // 117
        "Rouge Plaza",  // 118
        "Hotel Richissime",  // 119
        "Rouge Pokémon Center",  // 120
        "Centrico Pokémon Center",  // 121
        "Jaune Plaza",  // 122
        "Justice Dojo",  // 123
        "Jaune Pokémon Center",  // 124
        "Hibernal Pokémon Center",  // 125
        "Hair Salon",  // 126
        "Stone Emporium",  // 127
        "Poké Ball Boutique",  // 128
        "Changing Gears",  // 129
        "Boutique Couture",  // 130
        "Restaurant Le Nah",  // 131
        "Café Cyclone",  // 132
        "Café Classe",  // 133
        "Café Introversion",  // 134
        "Empty Room (Abandoned Building)",  // 135
        "Sewer Entrance",  // 136
        "Fresh Fits",  // 137
        "BRAVELY",  // 138
        "Dessert du Moment",  // 139
        "Marché Bleu",  // 140
        "In the Zone",  // 141
        "Kickspin",  // 142
        "Triathlon Bleu",  // 143
        "DEFOG Eyewear",  // 144
        "Équipement",  // 145
        "Coiffure Clips",  // 146
        "Café Woof",  // 147
        "Café Soleil",  // 148
        "Shutterbug Café",  // 149
        "Lumiose Sewers",  // 150
        "Café Pokémon-Amie",  // 151
        "Café Rouleau",  // 152
        "Café Gallant",  // 153
        "Café Triste",  // 154
        "The Usual",  // 155
        "Énergie",  // 156
        "Le Passe-temps",  // 157
        "Porte-Chance",  // 158
        "Pinceau",  // 159
        "Naptime",  // 160
        "Soil and Sneaks",  // 161
        "Marquage",  // 162
        "Glammor Girli",  // 163
        "Glammor Pretti",  // 164
        "Glammor Sporti",  // 165
        "NIGHTSIDE",  // 166
        "Bundle Up",  // 167
        "Midnight Rite",  // 168
        "Mode Mature",  // 169
        "Wisp",  // 170
        "Mode Magnifique",  // 171
        "FILMFAN",  // 172
        "DENSOKU Lumiose",  // 173
        "Les Chaussures",  // 174
        "Atelier Heads",  // 175
        "Glammor Cuti",  // 176
        "Kikonashi",  // 177
        "SUBATOMIC",  // 178
        "SUBATOMIC 4",  // 179
        "Masterpiece",  // 180
        "Le Pays des Vêtements",  // 181
        "Triathlon Rouge",  // 182
        "Le Pays des Pieds",  // 183
        "La Tornade",  // 184
        "Restaurant Le Yeah",  // 185
        "Sushi High Roller",  // 186
        "Restaurant Le Wow",  // 187
        "Lumiose Sewers",  // 188
        "Café Kizuna",  // 189
        "Café Ultimo",  // 190
        "Café Action!",  // 191
        "Café Bataille",  // 192
        "Wild Zone 17",  // 193
        "Wild Zone 1",  // 194
        "Wild Zone 2",  // 195
        "Wild Zone 12",  // 196
        "Wild Zone 10",  // 197
        "Wild Zone 5",  // 198
        "Wild Zone 16",  // 199
        "Wild Zone 14",  // 200
        "Wild Zone 9",  // 201
        "Wild Zone 18",  // 202
        "Wild Zone 7",  // 203
        "Wild Zone 13",  // 204
        "Wild Zone 4",  // 205
        "Wild Zone 3",  // 206
        "Wild Zone 15",  // 207
        "Wild Zone 19",  // 208
        "Wild Zone 6",  // 209
        "Wild Zone 11",  // 210
        "Wild Zone 8",  // 211
        "Wild Zone 20",  // 212
        "Battle Zone",  // 213
        "Passage de la Félicité",  // 214
        "Passage Ombragé",  // 215
        "Galerie de la Lune",  // 216
        "Passage du Palais",  // 217
        "Justice Dojo",  // 218
        "Hotel Z",  // 219
        "Racine Construction",  // 220
        "Hotel Richissime",  // 221
        "Rust Syndicate Office",  // 222
        "Gare de Lumiose",  // 223
        "Quasartico Inc.",  // 224
        "Restaurant Le Nah",  // 225
        "Restaurant Le Yeah",  // 226
        "Restaurant Le Wow",  // 227
        "Sushi High Roller",  // 228
        "Looker Bureau",  // 229
        "Pokémon Research Lab",  // 230
        "Old Building",  // 231
        "Lumiose Museum",  // 232
        "Lysandre Café",  // 233
        "Lysandre Labs",  // 234
        "The Sewers",  // 235
        "Room 201",  // 236
        "Room 202",  // 237
        "Room 203",  // 238
        "Room 204",  // 239
        "",  // 240
        "",  // 241
        "",  // 242
        "",  // 243
        "",  // 244
        "",  // 245
        "",  // 246
        "",  // 247
        "",  // 248
        "",  // 249
        "",  // 250
        "",  // 251
        "",  // 252
        "",  // 253
        "",  // 254
        "",  // 255
        "",  // 256
        "",  // 257
        "",  // 258
        "",  // 259
        "",  // 260
        "",  // 261
        "",  // 262
        "",  // 263
        "",  // 264
        "",  // 265
        "",  // 266
        "",  // 267
        "",  // 268
        "",  // 269
        "",  // 270
        "",  // 271
        "",  // 272
        "Hyperspace Lumiose",  // 273
        "Hyperspace Entry Point",  // 274
        "Hyperspace Disaster Arena",  // 275
        "Hyperspace Hunting Grounds",  // 276
        "Hyperspace Sushi Paradise",  // 277
        "Hyperspace Second-Sight Arena",  // 278
        "Hyperspace Infernal Arena",  // 279
        "Hyperspace Newmoon Nightmare",  // 280
        "Hyperspace Primordial Sea",  // 281
        "Hyperspace Desolate Land",  // 282
        "Hyperspace Sky Pillar",  // 283
    };

    // Gen 3 R/S/E + FR/LG (SA=1, RU=2, EM=3, FR=4, LG=5)
    // Source: PKHeX text_rsefrlg_00000_en.txt  (256 entries)
    static const char* const G3_LOC_NAMES[] = {
        "Littleroot Town",  // 0
        "Oldale Town",  // 1
        "Dewford Town",  // 2
        "Lavaridge Town",  // 3
        "Fallarbor Town",  // 4
        "Verdanturf Town",  // 5
        "Pacifidlog Town",  // 6
        "Petalburg City",  // 7
        "Slateport City",  // 8
        "Mauville City",  // 9
        "Rustboro City",  // 10
        "Fortree City",  // 11
        "Lilycove City",  // 12
        "Mossdeep City",  // 13
        "Sootopolis City",  // 14
        "Ever Grande City",  // 15
        "Route 101",  // 16
        "Route 102",  // 17
        "Route 103",  // 18
        "Route 104",  // 19
        "Route 105",  // 20
        "Route 106",  // 21
        "Route 107",  // 22
        "Route 108",  // 23
        "Route 109",  // 24
        "Route 110",  // 25
        "Route 111",  // 26
        "Route 112",  // 27
        "Route 113",  // 28
        "Route 114",  // 29
        "Route 115",  // 30
        "Route 116",  // 31
        "Route 117",  // 32
        "Route 118",  // 33
        "Route 119",  // 34
        "Route 120",  // 35
        "Route 121",  // 36
        "Route 122",  // 37
        "Route 123",  // 38
        "Route 124",  // 39
        "Route 125",  // 40
        "Route 126",  // 41
        "Route 127",  // 42
        "Route 128",  // 43
        "Route 129",  // 44
        "Route 130",  // 45
        "Route 131",  // 46
        "Route 132",  // 47
        "Route 133",  // 48
        "Route 134",  // 49
        "Underwater (Route 124)",  // 50
        "Underwater (Route 126)",  // 51
        "Underwater (Route 127)",  // 52
        "Underwater (Route 128)",  // 53
        "Underwater (Sootopolis City)",  // 54
        "Granite Cave",  // 55
        "Mt. Chimney",  // 56
        "Safari Zone (RSE)",  // 57
        "Battle Tower (RS) / Battle Frontier (E)",  // 58
        "Petalburg Woods",  // 59
        "Rusturf Tunnel",  // 60
        "Abandoned Ship",  // 61
        "New Mauville",  // 62
        "Meteor Falls",  // 63
        "Meteor Falls (unused)",  // 64
        "Mt. Pyre",  // 65
        "Hideout",  // 66
        "Shoal Cave",  // 67
        "Seafloor Cavern",  // 68
        "Underwater (Seafloor Cavern)",  // 69
        "Victory Road (RSE)",  // 70
        "Mirage Island",  // 71
        "Cave of Origin",  // 72
        "Southern Island",  // 73
        "Fiery Path",  // 74
        "Fiery Path (unused)",  // 75
        "Jagged Pass",  // 76
        "Jagged Pass (unused)",  // 77
        "Sealed Chamber",  // 78
        "Underwater (Route 134)",  // 79
        "Scorched Slab",  // 80
        "Island Cave",  // 81
        "Desert Ruins",  // 82
        "Ancient Tomb",  // 83
        "Inside of Truck",  // 84
        "Sky Pillar",  // 85
        "Secret Base",  // 86
        "Ferry",  // 87
        "Pallet Town",  // 88
        "Viridian City",  // 89
        "Pewter City",  // 90
        "Cerulean City",  // 91
        "Lavender Town",  // 92
        "Vermilion City",  // 93
        "Celadon City",  // 94
        "Fuchsia City",  // 95
        "Cinnabar Island",  // 96
        "Indigo Plateau",  // 97
        "Saffron City",  // 98
        "Route 4 (Pokémon Center)",  // 99
        "Route 10 (Pokémon Center)",  // 100
        "Route 1",  // 101
        "Route 2",  // 102
        "Route 3",  // 103
        "Route 4",  // 104
        "Route 5",  // 105
        "Route 6",  // 106
        "Route 7",  // 107
        "Route 8",  // 108
        "Route 9",  // 109
        "Route 10",  // 110
        "Route 11",  // 111
        "Route 12",  // 112
        "Route 13",  // 113
        "Route 14",  // 114
        "Route 15",  // 115
        "Route 16",  // 116
        "Route 17",  // 117
        "Route 18",  // 118
        "Route 19",  // 119
        "Route 20",  // 120
        "Route 21",  // 121
        "Route 22",  // 122
        "Route 23",  // 123
        "Route 24",  // 124
        "Route 25",  // 125
        "Viridian Forest",  // 126
        "Mt. Moon",  // 127
        "S.S. Anne",  // 128
        "Underground Path (Routes 5-6)",  // 129
        "Underground Path (Routes 7-8)",  // 130
        "Diglett's Cave",  // 131
        "Victory Road (Kanto)",  // 132
        "Rocket Hideout",  // 133
        "Silph Co.",  // 134
        "Pokémon Mansion",  // 135
        "Safari Zone (Kanto)",  // 136
        "Pokémon League",  // 137
        "Rock Tunnel",  // 138
        "Seafoam Islands",  // 139
        "Pokémon Tower",  // 140
        "Cerulean Cave",  // 141
        "Power Plant",  // 142
        "One Island",  // 143
        "Two Island",  // 144
        "Three Island",  // 145
        "Four Island",  // 146
        "Five Island",  // 147
        "Seven Island",  // 148
        "Six Island",  // 149
        "Kindle Road",  // 150
        "Treasure Beach",  // 151
        "Cape Brink",  // 152
        "Bond Bridge",  // 153
        "Three Isle Port",  // 154
        "Sevii Isle 6",  // 155
        "Sevii Isle 7",  // 156
        "Sevii Isle 8",  // 157
        "Sevii Isle 9",  // 158
        "Resort Gorgeous",  // 159
        "Water Labyrinth",  // 160
        "Five Isle Meadow",  // 161
        "Memorial Pillar",  // 162
        "Outcast Island",  // 163
        "Green Path",  // 164
        "Water Path",  // 165
        "Ruin Valley",  // 166
        "Trainer Tower (exterior)",  // 167
        "Canyon Entrance",  // 168
        "Sevault Canyon",  // 169
        "Tanoby Ruins",  // 170
        "Sevii Isle 22",  // 171
        "Sevii Isle 23",  // 172
        "Sevii Isle 24",  // 173
        "Navel Rock (FRLG)",  // 174
        "Mt. Ember",  // 175
        "Berry Forest",  // 176
        "Icefall Cave",  // 177
        "Rocket Warehouse",  // 178
        "Trainer Tower",  // 179
        "Dotted Hole",  // 180
        "Lost Cave",  // 181
        "Pattern Bush",  // 182
        "Altering Cave (FRLG)",  // 183
        "Tanoby Chambers",  // 184
        "Three Isle Path",  // 185
        "Tanoby Key",  // 186
        "Birth Island (FRLG)",  // 187
        "Monean Chamber",  // 188
        "Liptoo Chamber",  // 189
        "Weepth Chamber",  // 190
        "Dilford Chamber",  // 191
        "Scufib Chamber",  // 192
        "Rixy Chamber",  // 193
        "Viapois Chamber",  // 194
        "Ember Spa",  // 195
        "Celadon Dept. (FRLG) / Special Area (E)",  // 196
        "Aqua Hideout",  // 197
        "Magma Hideout",  // 198
        "Mirage Tower",  // 199
        "Birth Island (E)",  // 200
        "Faraway Island",  // 201
        "Artisan Cave",  // 202
        "Marine Cave",  // 203
        "Underwater (Marine Cave)",  // 204
        "Terra Cave",  // 205
        "Underwater (Route 105)",  // 206
        "Underwater (Route 125)",  // 207
        "Underwater (Route 129)",  // 208
        "Desert Underpass",  // 209
        "Altering Cave (E)",  // 210
        "Navel Rock (E)",  // 211
        "Trainer Hill",  // 212
        "",  // 213
        "",  // 214
        "",  // 215
        "",  // 216
        "",  // 217
        "",  // 218
        "",  // 219
        "",  // 220
        "",  // 221
        "",  // 222
        "",  // 223
        "",  // 224
        "",  // 225
        "",  // 226
        "",  // 227
        "",  // 228
        "",  // 229
        "",  // 230
        "",  // 231
        "",  // 232
        "",  // 233
        "",  // 234
        "",  // 235
        "",  // 236
        "",  // 237
        "",  // 238
        "",  // 239
        "",  // 240
        "",  // 241
        "",  // 242
        "",  // 243
        "",  // 244
        "",  // 245
        "",  // 246
        "",  // 247
        "",  // 248
        "",  // 249
        "",  // 250
        "",  // 251
        "",  // 252
        "(gift egg)",  // 253
        "(in-game trade)",  // 254
        "(fateful encounter)",  // 255
    };

    // Returns table[id] when in range, else "".
    static const char* lookup(const char* const* table, size_t count, uint16_t id) {
        return id < count ? table[id] : "";
    }

    const char* getMetLocationName(uint8_t originVersion, uint16_t locationId) {
        switch (originVersion) {
            case 42: case 43:
                return lookup(GG_LOC_NAMES, sizeof(GG_LOC_NAMES) / sizeof(GG_LOC_NAMES[0]), locationId);
            case 44: case 45:
                return lookup(SWSH_LOC_NAMES, sizeof(SWSH_LOC_NAMES) / sizeof(SWSH_LOC_NAMES[0]), locationId);
            case 47:
                return lookup(PLA_LOC_NAMES, sizeof(PLA_LOC_NAMES) / sizeof(PLA_LOC_NAMES[0]), locationId);
            case 48: case 49:
                return lookup(BDSP_LOC_NAMES, sizeof(BDSP_LOC_NAMES) / sizeof(BDSP_LOC_NAMES[0]), locationId);
            case 50: case 51:
                return lookup(SV_LOC_NAMES, sizeof(SV_LOC_NAMES) / sizeof(SV_LOC_NAMES[0]), locationId);
            case 52:
                return lookup(ZA_LOC_NAMES, sizeof(ZA_LOC_NAMES) / sizeof(ZA_LOC_NAMES[0]), locationId);
            case 1: case 2: case 3: case 4: case 5:
                return lookup(G3_LOC_NAMES, sizeof(G3_LOC_NAMES) / sizeof(G3_LOC_NAMES[0]), locationId);
            default:
                return "";
        }
    }

    // Raw table + size for a given origin, so a picker can enumerate the locations.
    LocationTable getLocationTable(uint8_t originVersion) {
        switch (originVersion) {
            case 42: case 43:
                return { GG_LOC_NAMES, sizeof(GG_LOC_NAMES) / sizeof(GG_LOC_NAMES[0]) };
            case 44: case 45:
                return { SWSH_LOC_NAMES, sizeof(SWSH_LOC_NAMES) / sizeof(SWSH_LOC_NAMES[0]) };
            case 47:
                return { PLA_LOC_NAMES, sizeof(PLA_LOC_NAMES) / sizeof(PLA_LOC_NAMES[0]) };
            case 48: case 49:
                return { BDSP_LOC_NAMES, sizeof(BDSP_LOC_NAMES) / sizeof(BDSP_LOC_NAMES[0]) };
            case 50: case 51:
                return { SV_LOC_NAMES, sizeof(SV_LOC_NAMES) / sizeof(SV_LOC_NAMES[0]) };
            case 52:
                return { ZA_LOC_NAMES, sizeof(ZA_LOC_NAMES) / sizeof(ZA_LOC_NAMES[0]) };
            case 1: case 2: case 3: case 4: case 5:
                return { G3_LOC_NAMES, sizeof(G3_LOC_NAMES) / sizeof(G3_LOC_NAMES[0]) };
            default:
                return { nullptr, 0 };
        }
    }
}
