#include "Legacy/RetroArchGSCDiscovery.h"
#include "Utils/SHA256.h"
#include <algorithm>
#include <array>
#include <cctype>
#include <cstdio>
#include <dirent.h>
#include <set>
#include <sys/stat.h>

namespace PokeVault::Legacy { namespace {
using namespace Integration::Gen2;
enum class Hint { None, Gold, Silver, Crystal, Ambiguous };
std::string trim(std::string s){auto ns=[](unsigned char c){return !std::isspace(c);};s.erase(s.begin(),std::find_if(s.begin(),s.end(),ns));s.erase(std::find_if(s.rbegin(),s.rend(),ns).base(),s.end());return s;}
std::string dir(const std::string&p){auto n=p.find_last_of("/\\");return n==std::string::npos?".":p.substr(0,n);}
std::string join(const std::string&a,const std::string&b){return a.empty()||a.back()=='/'||a.back()=='\\'?a+b:a+"/"+b;}
bool absPath(const std::string&p){return !p.empty()&&(p.front()=='/'||p.find(":/")!=std::string::npos);}
bool statFile(const std::string&p,struct stat*o=nullptr){struct stat s{};if(stat(p.c_str(),&s)||!S_ISREG(s.st_mode))return false;if(o)*o=s;return true;}
bool isDir(const std::string&p){struct stat s{};return stat(p.c_str(),&s)==0&&S_ISDIR(s.st_mode);}
std::string norm(std::string p){std::replace(p.begin(),p.end(),'\\','/');std::string r;bool slash=false;for(char c:p){if(c=='/'){if(slash)continue;slash=true;}else slash=false;r+=c;}while(r.size()>1&&r.back()=='/')r.pop_back();return r;}
std::string sha(const uint8_t*b,size_t n){Utils::SHA256 h;h.update(b,n);std::array<uint8_t,Utils::PKSE_SHA256_HASH_SIZE>d{};h.finalize(d.data());static constexpr char x[]="0123456789abcdef";std::string r;for(auto v:d){r+=x[v>>4];r+=x[v&15];}return r;}
std::string fsid(const std::string&p){struct stat s{};if(!stat(p.c_str(),&s)&&s.st_ino)return "inode:"+std::to_string((unsigned long long)s.st_dev)+":"+std::to_string((unsigned long long)s.st_ino);return norm(p);}
std::string sid(const std::string&p){auto v="retroarch:"+norm(p);return sha(reinterpret_cast<const uint8_t*>(v.data()),v.size());}
bool extOK(const std::string&n){auto p=n.find_last_of('.');if(p==std::string::npos)return false;auto e=n.substr(p);std::transform(e.begin(),e.end(),e.begin(),[](unsigned char c){return(char)std::tolower(c);});return e==".sav"||e==".srm";}
std::string compact(const std::string&p){std::string r;for(unsigned char c:p)if(std::isalnum(c))r+=(char)std::tolower(c);return r;}
Hint hint(const std::string&p){auto c=compact(p);if(c.find("heartgold")!=std::string::npos||c.find("soulsilver")!=std::string::npos)return Hint::None;bool g=c.find("pokemongold")!=std::string::npos||c.find("pokegold")!=std::string::npos;bool s=c.find("pokemonsilver")!=std::string::npos||c.find("pokesilver")!=std::string::npos;bool y=c.find("pokemoncrystal")!=std::string::npos||c.find("pokecrystal")!=std::string::npos;std::string t;for(size_t i=0;i<=p.size();++i){unsigned char ch=i<p.size()?(unsigned char)p[i]:'/';if(std::isalnum(ch)){t+=(char)std::tolower(ch);continue;}if(t=="gold")g=true;else if(t=="silver")s=true;else if(t=="crystal")y=true;t.clear();}if((int)g+(int)s+(int)y>1)return Hint::Ambiguous;if(g)return Hint::Gold;if(s)return Hint::Silver;if(y)return Hint::Crystal;return Hint::None;}
SourceGame game(Hint h){return h==Hint::Silver?SourceGame::Silver:h==Hint::Crystal?SourceGame::Crystal:SourceGame::Gold;}
bool sizeOK(size_t n){if(n==kRawSaveSize32K||n==kRawSaveSize64K)return true;for(size_t b:{kRawSaveSize32K,kRawSaveSize64K})if(n>b&&isKnownRTCFooterSize(n-b))return true;return false;}
bool readFile(const std::string&p,size_t n,std::vector<uint8_t>&v){FILE*f=std::fopen(p.c_str(),"rb");if(!f)return false;v.resize(n);size_t got=n?std::fread(v.data(),1,n,f):0;int extra=std::fgetc(f);bool ok=std::fclose(f)==0;if(got!=n||extra!=EOF||!ok){v.clear();return false;}return true;}
struct Families{std::shared_ptr<const ReadOnlySave>gs,c;SaveError err=SaveError::None;std::string detail;};
Families families(std::span<const uint8_t>b){Families f;auto g=parse(b,SourceGame::Gold);if(g)f.gs=std::move(g.save);auto c=parse(b,SourceGame::Crystal);if(c)f.c=std::move(c.save);if(!f.gs&&!f.c){auto&x=g.error==SaveError::GameHintMismatch?c:g;f.err=x.error;f.detail=x.detail;}return f;}
GSCSource inspect(const std::string&p,const struct stat&m,Hint h){GSCSource s;s.path=p;s.normalizedPath=norm(p);s.sourceIdentity=sid(p);s.fileSize=(uint64_t)m.st_size;s.modifiedTime=(int64_t)m.st_mtime;if(m.st_size<0||!sizeOK((size_t)m.st_size)){s.status=GSCSourceStatus::InvalidSave;s.parseError=SaveError::WrongSize;s.detail="candidate is not a supported Gen II battery-save/RTC-wrapper size";return s;}std::vector<uint8_t>b;if(!readFile(p,(size_t)m.st_size,b)){s.detail="candidate could not be read completely";return s;}s.contentFingerprint=sha(b.data(),b.size());if(h==Hint::None||h==Hint::Ambiguous){auto f=families(b);if(!f.gs&&!f.c){s.status=GSCSourceStatus::InvalidSave;s.parseError=f.err;s.detail=f.detail;return s;}if(h==Hint::Ambiguous){s.status=GSCSourceStatus::AmbiguousIdentity;s.detail="valid Gen II save path contains multiple Gold/Silver/Crystal identity hints";return s;}if(f.c&&!f.gs){s.status=GSCSourceStatus::Ready;s.gameId=sourceGameId(SourceGame::Crystal);s.save=f.c;s.detail="validated structural Crystal source";return s;}s.status=GSCSourceStatus::AmbiguousIdentity;s.detail="valid Gold/Silver-family save needs a trusted Gold or Silver source hint";return s;}auto r=parse(b,game(h));if(!r){s.status=r.error==SaveError::GameHintMismatch?GSCSourceStatus::AmbiguousIdentity:GSCSourceStatus::InvalidSave;s.parseError=r.error;s.detail=r.detail;return s;}s.status=GSCSourceStatus::Ready;s.gameId=sourceGameId(game(h));s.save=std::move(r.save);s.detail=std::string("validated read-only RetroArch Generation II source (")+familyName(s.save->metadata().family)+", "+regionName(s.save->metadata().region)+")";return s;}
struct State{GSCScanLimits lim;GSCDiscoveryResult r;std::set<std::string>dirs,files;};
void scan(const std::string&root,size_t depth,State&s){if(s.r.limitReached||depth>s.lim.maxDepth||!s.dirs.insert(fsid(root)).second)return;DIR*d=opendir(root.c_str());if(!d)return;std::vector<std::string>names;while(auto*e=readdir(d))if(std::string(e->d_name)!="."&&std::string(e->d_name)!="..")names.emplace_back(e->d_name);closedir(d);std::sort(names.begin(),names.end());for(auto&n:names){if(s.r.limitReached)break;auto p=join(root,n);if(isDir(p)){if(depth<s.lim.maxDepth)scan(p,depth+1,s);continue;}if(!extOK(n))continue;struct stat m{};if(!statFile(p,&m)||!s.files.insert(fsid(p)).second)continue;if(s.r.filesExamined>=s.lim.maxFiles){s.r.limitReached=true;break;}++s.r.filesExamined;auto h=hint(p);auto src=inspect(p,m,h);src.canonicalPath=fsid(p);if(src.ready()||src.status==GSCSourceStatus::AmbiguousIdentity||h!=Hint::None)s.r.sources.push_back(std::move(src));}}
} // namespace

std::vector<std::string> retroArchGSCSaveRootsFromConfig(const std::string&cfg){std::vector<std::string>r;FILE*f=std::fopen(cfg.c_str(),"rb");if(!f)return r;char line[2048];while(std::fgets(line,sizeof(line),f)){std::string v(line);auto e=v.find('=');if(e==std::string::npos||trim(v.substr(0,e))!="savefile_directory")continue;v=trim(v.substr(e+1));if(v.size()>=2&&v.front()=='"'&&v.back()=='"')v=v.substr(1,v.size()-2);if(!v.empty()&&v!="default")r.push_back(absPath(v)?v:join(dir(cfg),v));break;}std::fclose(f);return r;}
GSCDiscoveryResult discoverGSCSaves(std::span<const std::string> roots,GSCScanLimits lim){if(!lim.maxFiles)lim.maxFiles=1;State s{lim,{},{},{}};for(auto&r:roots){if(s.r.limitReached)break;if(isDir(r)){if(s.r.activeRoot.empty())s.r.activeRoot=norm(r);scan(r,0,s);}}return std::move(s.r);}
GSCDiscoveryResult discoverConfiguredRetroArchGSCSaves(GSCScanLimits lim,const std::string&cfg,const std::string&fallback){auto roots=retroArchGSCSaveRootsFromConfig(cfg);std::vector<std::string>use;auto kind=GSCDiscoveryResult::RootKind::None;if(!roots.empty()&&isDir(roots.front())){use.push_back(roots.front());kind=GSCDiscoveryResult::RootKind::Configured;}else if(isDir(fallback)){use.push_back(fallback);kind=GSCDiscoveryResult::RootKind::ConventionalFallback;}auto r=discoverGSCSaves(use,lim);r.activeRootKind=kind;return r;}
} // namespace PokeVault::Legacy
