#!/usr/bin/env python3
"""Generate released international Gen I static/trade legality evidence from pinned PKHeX."""

from __future__ import annotations

import os
import re

import pkhex_source

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "include", "Legality", "Gen1EncounterEvidenceData.inc")
SOURCE = "Legality/Encounters/Data/Gen1/Encounters1.cs"

STATIC_TABLES = (("StaticRBY", 0x07), ("StaticRB", 0x03), ("StaticYW", 0x04))
TRADE_TABLES = (("TradeGift_RB", 0x03), ("TradeGift_YW", 0x04))

def strip_comments(text: str) -> str:
    return "\n".join(re.sub(r"//.*$", "", line) for line in text.splitlines())

def section(source: str, name: str, type_name: str) -> str:
    pattern = re.compile(
        re.escape(type_name) + r"\[\]\s+" + re.escape(name) +
        r"\s*=\s*\[([\s\S]*?)\n\s*\];"
    )
    match = pattern.search(strip_comments(source))
    if not match:
        raise ValueError("missing Gen I table %s" % name)
    return match.group(1)

def parse_statics(source: str, table: str, mask: int):
    body = section(source, table, "EncounterStatic1")
    for species, level, _version in re.findall(
        r"new\(\s*(\d+)\s*,\s*(\d+)\s*,\s*([A-Za-z]+)\s*\)", body
    ):
        yield int(species), int(level), mask

def parse_trades(source: str, table: str, mask: int):
    body = section(source, table, "EncounterTrade1")
    pattern = re.compile(
        r"new\(TradeNames,\s*\d+,\s*(\d+),\s*([A-Za-z]+),\s*(\d+)"
        r"(?:\s*,\s*(\d+))?\s*\)(?:\s*\{([^}]*)\})?"
    )
    for species, _version, rby, gsc, fields in pattern.findall(body):
        level_rby = int(rby)
        level_gsc = int(gsc) if gsc else level_rby
        evolves = bool(re.search(r"EvolveOnTrade\s*=\s*true", fields or ""))
        yield int(species), level_rby, level_gsc, mask, evolves

def main() -> int:
    with open(pkhex_source.pkhex_path(SOURCE), encoding="utf-8") as handle:
        source = handle.read()

    statics = [row for table, mask in STATIC_TABLES for row in parse_statics(source, table, mask)]
    trades = [row for table, mask in TRADE_TABLES for row in parse_trades(source, table, mask)]
    if len(statics) != 31:
        raise ValueError("expected 31 released international Gen I static rows")
    if len(trades) != 17:
        raise ValueError("expected 17 released international Gen I trade rows")

    lines = [
        "// GENERATED by tools/gen_legality_gen1_encounters.py.",
        "// Source: PKHeX @ %s" % pkhex_source._REF,
        "// International Red/Blue/Yellow only. Japanese Blue (BU) is intentionally excluded.",
        "inline constexpr std::array<StaticEntry, 31> kStaticEntries{{",
    ]
    for species, level, mask in statics:
        lines.append("    {%d, %d, 0x%02x}," % (species, level, mask))
    lines.extend(["}};", "", "inline constexpr std::array<TradeEntry, 17> kTradeEntries{{"])
    for species, rby, gsc, mask, evolves in trades:
        lines.append("    {%d, %d, %d, 0x%02x, %s}," %
                     (species, rby, gsc, mask, "true" if evolves else "false"))
    lines.extend(["}};", ""])

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))
    print("wrote %d static and %d trade Gen I rows to %s" %
          (len(statics), len(trades), OUT))
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
