#!/usr/bin/env python3
"""Generate Gen II fixed in-game trade legality evidence from pinned PKHeX source."""
from __future__ import annotations
import os,re
import pkhex_source
ROOT=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT=os.path.join(ROOT,"include","Legality","Gen2TradeEvidenceData.inc")
SOURCE="Legality/Encounters/Data/Gen2/Encounters2.cs"

def main():
    with open(pkhex_source.pkhex_path(SOURCE),encoding="utf-8") as fh: source=fh.read()
    m=re.search(r"internal static readonly EncounterTrade2\[\]\s+TradeGift_GSC\s*=\s*\[([\s\S]*?)\n\s*\];",source)
    if not m: raise ValueError("missing TradeGift_GSC")
    body="\n".join(re.sub(r"//.*$","",line) for line in m.group(1).splitlines())
    rows=[]
    pattern=re.compile(r"new\(TradeNames,\s*(\d+),\s*(\d+),\s*(\d+),\s*(\d+)\)\s*(?:\{([\s\S]*?)\})?")
    for x in pattern.finditer(body):
        idx,species,level,tid=map(int,x.group(1,2,3,4)); fields=x.group(5) or ""
        iv=re.search(r"\bIVs\s*=\s*new\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)",fields)
        fixed=iv is not None
        atk=int(iv.group(2)) if fixed else 0
        de=int(iv.group(3)) if fixed else 0
        spe=int(iv.group(4)) if fixed else 0
        spa=int(iv.group(5)) if fixed else 0
        rows.append((idx,species,level,tid,int(fixed),atk,de,spe,spa))
    if len(rows)!=11: raise ValueError("expected 11 trades, got %d" % len(rows))
    def pack(r):
        idx,species,level,tid,fixed,atk,de,spe,spa=r
        return species | (level<<8) | (fixed<<15) | (tid<<16) | (atk<<32) | \
               (de<<36) | (spe<<40) | (spa<<44) | (idx<<48)
    vals=[pack(r) for r in rows]
    lines=[
      "// GENERATED by tools/gen_legality_gen2_trades.py.",
      "// Source: PKHeX @ %s" % pkhex_source._REF,
      "// Source table: Encounters2.cs TradeGift_GSC.",
      "// Nickname/OT language strings are deliberately not packed yet.",
      "inline constexpr uint64_t kPackedGen2Trades[] = {",
    ]
    for i in range(0,len(vals),4):
        chunk=", ".join("0x%016xULL" % v for v in vals[i:i+4])
        if i+4<len(vals): chunk+=","
        lines.append("    "+chunk)
    lines.extend(["};",""])
    with open(OUT,"w",encoding="utf-8",newline="\n") as fh: fh.write("\n".join(lines))
    print("wrote %d Gen II trade rows to %s" % (len(rows),OUT))
    return 0
if __name__=="__main__": raise SystemExit(main())
