#!/usr/bin/env python3
"""Generate fixed Gen IV in-game trade legality evidence from pinned PKHeX source."""

from __future__ import annotations

import os
import re

import pkhex_source

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "include", "Legality", "Gen4TradeEvidenceData.inc")
LINK_TRADE_4_NPC = 2001  # PKHeX Locations.LinkTrade4NPC on the pinned reference.

SOURCES = (
    ("Legality/Encounters/Data/Gen4/Encounters4DPPt.cs", "TradeGift_DPPtIngame", "DPPt", 0x07),
    ("Legality/Encounters/Data/Gen4/Encounters4HGSS.cs", "TradeGift_HGSS", "HGSS", 0x18),
)

def strip_comments(text: str) -> str:
    return "\n".join(re.sub(r"//.*$", "", line) for line in text.splitlines())

def section(source: str, name: str) -> str:
    pattern = re.compile(
        r"EncounterTrade4PID\[\]\s+" + re.escape(name) + r"\s*=\s*\[([\s\S]*?)\n\s*\];"
    )
    match = pattern.search(strip_comments(source))
    if not match:
        raise ValueError("missing Gen IV trade table %s" % name)
    return match.group(1)

def parse_int(text: str) -> int:
    return int(text, 16) if text.lower().startswith("0x") else int(text, 10)

def parse_rows(source: str, table: str, tag: str, game_mask: int):
    body = section(source, table)
    pattern = re.compile(
        r"new\(TradeNames,\s*\d+,\s*" + re.escape(tag) +
        r",\s*(0x[0-9A-Fa-f]+|\d+),\s*(\d+),\s*(\d+)\)\s*\{([\s\S]*?)\},"
    )
    for match in pattern.finditer(body):
        pid, species, level, fields = match.groups()
        def required(name: str) -> int:
            found = re.search(r"\b" + name + r"\s*=\s*(0x[0-9A-Fa-f]+|\d+)", fields)
            if not found:
                raise ValueError("missing %s in %s" % (name, table))
            return parse_int(found.group(1))
        iv_match = re.search(r"\bIVs\s*=\s*new\(([^)]*)\)", fields)
        if not iv_match:
            raise ValueError("missing IVs in %s" % table)
        ivs = [parse_int(v.strip()) for v in iv_match.group(1).split(",")]
        if len(ivs) != 6:
            raise ValueError("expected six IVs")
        iv_pack = sum((value & 31) << (index * 5) for index, value in enumerate(ivs))
        met_match = re.search(r"\bMetLocation\s*=\s*(\d+)", fields)
        met_location = parse_int(met_match.group(1)) if met_match else LINK_TRADE_4_NPC
        tid = required("TID16")
        sid = required("SID16")
        ability_match = re.search(r"\bAbility\s*=\s*(OnlyFirst|OnlySecond)", fields)
        if not ability_match:
            raise ValueError("missing fixed ability slot in %s" % table)
        ability_number = 1 if ability_match.group(1) == "OnlyFirst" else 2
        yield (
            parse_int(pid), tid | (sid << 16), iv_pack, parse_int(species),
            met_location, parse_int(level), required("Gender"), required("OTGender"),
            ability_number, game_mask,
        )

def main() -> int:
    rows = []
    for path, table, tag, mask in SOURCES:
        with open(pkhex_source.pkhex_path(path), encoding="utf-8") as handle:
            rows.extend(parse_rows(handle.read(), table, tag, mask))
    if len(rows) != 16:
        raise ValueError("expected 16 Gen IV in-game trade rows, got %d" % len(rows))

    lines = [
        "// GENERATED by tools/gen_legality_gen4_trades.py.",
        "// Source: PKHeX @ %s" % pkhex_source._REF,
        "// Tables: TradeGift_DPPtIngame and TradeGift_HGSS.",
        "// Fixed first/second ability slot is persistent Gen IV trade evidence.",
        "// Source-species/game language-ID quirks are enforced by Gen4TradeEvidence.h.",
        "// Localized nickname/OT string matching remains a separate evidence layer.",
        "inline constexpr std::array<Entry, 16> kEntries{{",
    ]
    for pid, id32, iv_pack, species, met_location, level, gender, ot_gender, ability_number, mask in rows:
        lines.append(
            "    {0x%08xu, 0x%08xu, 0x%08xu, %d, %d, %d, %d, %d, %d, 0x%02x}," %
            (pid, id32, iv_pack, species, met_location, level, gender, ot_gender,
             ability_number, mask)
        )
    lines.extend(["}};", ""])
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))
    print("wrote 16 Gen IV in-game trade rows to %s" % OUT)
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
