#!/usr/bin/env python3
"""Generate compact Gen II wild legality evidence from pinned PKHeX resources."""

from __future__ import annotations
import os, struct
import pkhex_source

ROOT=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT=os.path.join(ROOT,"include","Legality","Gen2WildEncounterData.inc")
SOURCES=(
    ("gold_gbc","Resources/legality/wild/Gen2/encounter_gold.pkl",0),
    ("silver_gbc","Resources/legality/wild/Gen2/encounter_silver.pkl",1),
    ("crystal_gbc","Resources/legality/wild/Gen2/encounter_crystal.pkl",2),
)

def linker_entries(data: bytes):
    count=struct.unpack_from("<H",data,2)[0]
    for i in range(count):
        start=struct.unpack_from("<I",data,4+i*4)[0]
        end=struct.unpack_from("<I",data,8+i*4)[0]
        yield data[start:end]

def pack(game,location,time,kind,species,slot,min_level,max_level):
    return (species | (location<<8) | (time<<16) | (kind<<24) |
            (min_level<<28) | (max_level<<34) | (slot<<40) | (game<<44))

def main():
    packed=[]
    counts={}
    for game_id,path,game in SOURCES:
        with open(pkhex_source.pkhex_path(path),"rb") as handle:
            data=handle.read()
        n=0
        for area in linker_entries(data):
            location,time,kind,_rate=area[:4]
            slots=area[4:]
            if kind>1:
                count=len(slots)//5
                start=count
            else:
                count=len(slots)//4
                start=0
            for i in range(count):
                species,slot,min_level,max_level=slots[start+i*4:start+i*4+4]
                packed.append(pack(game,location,time,kind,species,slot,min_level,max_level))
                n+=1
        counts[game_id]=n

    expected={"gold_gbc":3272,"silver_gbc":3272,"crystal_gbc":3312}
    if counts!=expected:
        raise ValueError(f"unexpected Gen II wild counts: {counts}")

    lines=[
        "// GENERATED by tools/gen_legality_gen2_wild.py.",
        f"// Source: PKHeX @ {pkhex_source._REF}",
        "// Resources: encounter_gold.pkl, encounter_silver.pkl, encounter_crystal.pkl",
        "// Positive encounter evidence. Headbutt TID/tree availability and evolution reconstruction remain separate.",
        "inline constexpr uint64_t kPackedGen2WildEncounters[] = {",
    ]
    for i in range(0,len(packed),6):
        chunk=", ".join(f"0x{v:012x}ULL" for v in packed[i:i+6])
        if i+6<len(packed): chunk+=","
        lines.append("    "+chunk)
    lines.extend(["};",""])
    with open(OUT,"w",encoding="utf-8",newline="\n") as handle:
        handle.write("\n".join(lines))
    print(f"wrote {len(packed)} Gen II wild rows to {OUT}")
    return 0

if __name__=="__main__":
    raise SystemExit(main())
