#!/usr/bin/env python3
"""Generate compact Gen IV wild-encounter legality evidence from pinned PKHeX data."""

from __future__ import annotations

import os
import struct

import pkhex_source

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "include", "Legality", "Gen4WildEncounterData.inc")

GAMES = (
    ("diamond_nds", "Resources/legality/wild/Gen4/encounter_d.pkl", 0),
    ("pearl_nds", "Resources/legality/wild/Gen4/encounter_p.pkl", 1),
    ("platinum_nds", "Resources/legality/wild/Gen4/encounter_pt.pkl", 2),
    ("heartgold_nds", "Resources/legality/wild/Gen4/encounter_hg.pkl", 3),
    ("soulsilver_nds", "Resources/legality/wild/Gen4/encounter_ss.pkl", 4),
)


def entries(data: bytes):
    if len(data) < 8:
        raise ValueError("BinLinker resource is truncated")
    count = struct.unpack_from("<H", data, 2)[0]
    offsets = struct.unpack_from("<%dI" % (count + 1), data, 4)
    for i in range(count):
        start, end = offsets[i], offsets[i + 1]
        if start > end or end > len(data):
            raise ValueError("BinLinker entry offset is invalid")
        yield data[start:end]


def parse_game(path: str, game_index: int):
    with open(pkhex_source.pkhex_path(path), "rb") as handle:
        data = handle.read()
    rows = set()
    for area in entries(data):
        if len(area) < 6 or (len(area) - 6) % 10:
            raise ValueError("unexpected Gen IV encounter-area size")
        location = area[0]
        method = area[2]
        for offset in range(6, len(area), 10):
            species = struct.unpack_from("<H", area, offset)[0]
            form = area[offset + 2]
            slot = area[offset + 3]
            minimum = area[offset + 4]
            maximum = area[offset + 5]
            rows.add((game_index, species, location, minimum, maximum, method, form, slot))
    return rows


def pack(row):
    game, species, location, minimum, maximum, method, form, slot = row
    if slot > 0x0F:
        raise ValueError("Gen IV wild slot number exceeds packed 4-bit field")
    return (
        species
        | (location << 9)
        | (minimum << 17)
        | (maximum << 24)
        | (method << 31)
        | (form << 35)
        | (game << 43)
        | (slot << 46)
    )


def main() -> int:
    rows = set()
    for _name, path, game in GAMES:
        rows.update(parse_game(path, game))
    ordered = sorted(rows)

    lines = [
        "// GENERATED by tools/gen_legality_gen4_wild.py.",
        "// Source: PKHeX @ %s" % pkhex_source._REF,
        "// Resources: encounter_d/p/pt/hg/ss.pkl (BinLinker Gen IV wild slots).",
        "// Packed layout: species[0:8], location[9:16], min[17:23], max[24:30],",
        "// method[31:34], form[35:42], game[43:45], slot[46:49].",
        "// This is wild-slot evidence only. Static/gift/trade/event encounters are separate,",
        "// so absence from this table MUST NOT be interpreted as illegal.",
        "inline constexpr uint64_t kPackedGen4WildEncounters[] = {",
    ]
    packed = [pack(row) for row in ordered]
    for i in range(0, len(packed), 6):
        chunk = ", ".join("0x%012xULL" % value for value in packed[i:i + 6])
        if i + 6 < len(packed):
            chunk += ","
        lines.append("    " + chunk)
    lines.append("};")
    lines.append("")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))
    print("wrote %d unique Gen IV wild encounter rows to %s" % (len(ordered), OUT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
