#!/usr/bin/env python3
"""Generate Generation III XD shadow encounter identity evidence from pinned PKHeX source."""

from __future__ import annotations

import os
import re

import pkhex_source

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "include", "Legality", "Gen3XdShadowEncounterData.inc")
SOURCE = "Legality/Encounters/Data/Gen3/Encounters3XD.cs"

def main() -> int:
    with open(pkhex_source.pkhex_path(SOURCE), encoding="utf-8") as handle:
        source = handle.read()

    marker = "internal static readonly EncounterShadow3XD[] Shadow"
    start = source.find(marker)
    if start < 0:
        raise ValueError("missing XD shadow table")
    body = source[start:]
    body = body[:body.find("];")]

    rows = []
    pattern = re.compile(
        r"new\(\s*(\d+)\s*,\s*(\d+)\s*,\s*([A-Za-z0-9_]+)\s*\)\s*\{([^}]*)\}"
    )
    for match in pattern.finditer(body):
        index, gauge, team, fields = match.groups()
        species = re.search(r"\bSpecies\s*=\s*(\d+)", fields)
        level = re.search(r"\bLevel\s*=\s*(\d+)", fields)
        location = re.search(r"\bLocation\s*=\s*(\d+)", fields)
        if not species or not level or not location:
            raise ValueError("XD shadow row missing species/level/location")
        fixed = re.search(r"\bFixedBall\s*=\s*Ball\.([A-Za-z]+)", fields)
        fixed_ball = 4 if fixed and fixed.group(1) == "Poke" else 0
        if fixed and fixed.group(1) != "Poke":
            raise ValueError("unsupported XD fixed ball " + fixed.group(1))
        rows.append((
            int(index), int(species.group(1)), int(level.group(1)),
            int(location.group(1)), fixed_ball,
        ))

    if len(rows) != 90:
        raise ValueError("expected 90 XD shadow rows, got %d" % len(rows))

    lines = [
        "// GENERATED by tools/gen_legality_gen3_xd_shadows.py.",
        "// Source: PKHeX @ %s" % pkhex_source._REF,
        "// Source table: Encounters3XD.cs EncounterShadow3XD[] Shadow.",
        "// Team-lock aliases are intentionally not flattened here; recursive lock validation is a later layer.",
        "inline constexpr std::array<Entry, 90> kEntries{{",
    ]
    for index, species, level, location, fixed_ball in rows:
        lines.append(
            "    {%d, %d, %d, %d, %d}," %
            (index, species, level, location, fixed_ball)
        )
    lines.extend(["}};", ""])

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))
    print("wrote %d XD shadow rows to %s" % (len(rows), OUT))
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
