#!/usr/bin/env python3
"""Generate compact Gen II static/gift legality evidence from pinned PKHeX source."""

from __future__ import annotations
import os
import re
import pkhex_source

ROOT=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT=os.path.join(ROOT,"include","Legality","Gen2StaticEncounterData.inc")
SOURCE="Legality/Encounters/Data/Gen2/Encounters2.cs"
GAME_INDEX={"gold_gbc":0,"silver_gbc":1,"crystal_gbc":2}
TABLES={
    "StaticGSC":("gold_gbc","silver_gbc","crystal_gbc"),
    "StaticGS":("gold_gbc","silver_gbc"),
    "StaticGD":("gold_gbc",),
    "StaticSI":("silver_gbc",),
    "StaticC":("crystal_gbc",),
    "StaticOddEggC":("crystal_gbc",),
}

def section(source,name):
    m=re.search(r"public static readonly EncounterStatic2\[\]\s+"+re.escape(name)+
                r"\s*=\s*\[([\s\S]*?)\n\s*\];",source)
    if not m: raise ValueError("missing "+name)
    return m.group(1)

def main():
    with open(pkhex_source.pkhex_path(SOURCE),encoding="utf-8") as fh:
        source=fh.read()
    rows=set()
    for table,games in TABLES.items():
        body="\n".join(re.sub(r"//.*$","",line) for line in section(source,table).splitlines())
        for m in re.finditer(r"new\(\s*(\d+)\s*,\s*(\d+)\s*,\s*([A-Za-z]+)\s*\)\s*(?:\{([\s\S]*?)\})?",body):
            species,level=int(m.group(1)),int(m.group(2))
            fields=m.group(4) or ""
            loc=re.search(r"\bLocation\s*=\s*(\d+)",fields)
            location=int(loc.group(1)) if loc else 0
            egg=bool(re.search(r"\bIsEgg\s*=\s*true",fields))
            shiny=1 if re.search(r"\bShiny\s*=\s*Shiny\.Always",fields) else \
                  2 if re.search(r"\bShiny\s*=\s*Shiny\.Never",fields) else 0
            roaming=species in (243,244,245) and location==2
            for game in games:
                rows.add((GAME_INDEX[game],species,location,level,int(egg),shiny,int(roaming)))
    ordered=sorted(rows)
    def pack(r):
        game,species,location,level,egg,shiny,roaming=r
        return species | (location<<8) | (level<<15) | (egg<<22) | \
               (shiny<<23) | (roaming<<25) | (game<<26)
    packed=[pack(r) for r in ordered]
    lines=[
        "// GENERATED by tools/gen_legality_gen2_static.py.",
        "// Source: PKHeX @ %s" % pkhex_source._REF,
        "// Sources: Encounters2.cs StaticGSC/GS/GD/SI/C/OddEggC.",
        "// VC Celebi, external events, wild slots and fixed in-game trades are separate evidence layers.",
        "inline constexpr uint32_t kPackedGen2StaticEncounters[] = {",
    ]
    for i in range(0,len(packed),8):
        chunk=", ".join("0x%08xu" % v for v in packed[i:i+8])
        if i+8<len(packed): chunk+=","
        lines.append("    "+chunk)
    lines.extend(["};",""])
    os.makedirs(os.path.dirname(OUT),exist_ok=True)
    with open(OUT,"w",encoding="utf-8",newline="\n") as fh:
        fh.write("\n".join(lines))
    print("wrote %d Gen II static/gift rows to %s" % (len(ordered),OUT))
    return 0

if __name__=="__main__":
    raise SystemExit(main())
