#!/usr/bin/env python3
"""Generate compact Gen IV static/gift legality evidence from pinned PKHeX source."""

from __future__ import annotations

import os
import re

import pkhex_source

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "include", "Legality", "Gen4StaticEncounterData.inc")

SOURCES = (
    "Legality/Encounters/Data/Gen4/Encounters4DPPt.cs",
    "Legality/Encounters/Data/Gen4/Encounters4HGSS.cs",
)
BALL_INDEX = {
    "Poke": 4,
    "Safari": 5,
    "Cherish": 16,
}

GAME_INDEX = {
    "diamond_nds": 0,
    "pearl_nds": 1,
    "platinum_nds": 2,
    "heartgold_nds": 3,
    "soulsilver_nds": 4,
}
TABLES = {
    "StaticDPPt": {"DPPt": ("diamond_nds", "pearl_nds", "platinum_nds")},
    "StaticDP": {"DP": ("diamond_nds", "pearl_nds")},
    "StaticPt": {"Pt": ("platinum_nds",)},
    "StaticD": {"D": ("diamond_nds",)},
    "StaticP": {"P": ("pearl_nds",)},
    "Encounter_HGSS": {"HGSS": ("heartgold_nds", "soulsilver_nds")},
    "StaticHG": {"HG": ("heartgold_nds",)},
    "StaticSS": {"SS": ("soulsilver_nds",)},
}


def section(source: str, name: str) -> str:
    pattern = re.compile(
        r"(?:public|internal) static readonly EncounterStatic4\[\] "
        + re.escape(name)
        + r"\s*=\s*\[([\s\S]*?)\n\s*\];"
    )
    match = pattern.search(source)
    if not match:
        raise ValueError("missing Gen IV static table %s" % name)
    return match.group(1)


def parse_rows(source: str, table: str, tags: dict[str, tuple[str, ...]]):
    body = section(source, table)
    body = "\n".join(re.sub(r"//.*$", "", line) for line in body.splitlines())
    pattern = re.compile(r"new\(\s*([A-Za-z]+)\s*\)\s*\{([\s\S]*?)\}")
    for match in pattern.finditer(body):
        tag, fields = match.groups()
        species = re.search(r"\bSpecies\s*=\s*(\d+)", fields)
        level = re.search(r"\bLevel\s*=\s*(\d+)", fields)
        location = re.search(r"\bLocation\s*=\s*(\d+)", fields)
        if not species or not level or not location:
            continue
        form = re.search(r"\bForm\s*=\s*(\d+)", fields)
        egg = re.search(r"\bEggLocation\s*=\s*(\d+)", fields)
        roaming = bool(re.search(r"\bIsRoaming\s*=\s*true", fields))
        fixed_ball = re.search(r"\bFixedBall\s*=\s*Ball\.([A-Za-z]+)", fields)
        ball = BALL_INDEX[fixed_ball.group(1)] if fixed_ball else 0
        for game in tags.get(tag, ()):
            yield (
                GAME_INDEX[game],
                int(species.group(1)),
                int(location.group(1)),
                int(level.group(1)),
                int(form.group(1)) if form else 0,
                int(egg.group(1)) if egg else 0,
                roaming,
                ball,
            )


def pack(row) -> int:
    game, species, location, level, form, egg_location, roaming, fixed_ball = row
    return (
        species
        | (location << 9)
        | (level << 21)
        | (form << 28)
        | (egg_location << 36)
        | (int(roaming) << 48)
        | (game << 49)
        | (fixed_ball << 52)
    )


def main() -> int:
    texts = {}
    for path in SOURCES:
        with open(pkhex_source.pkhex_path(path), encoding="utf-8") as handle:
            texts[path] = handle.read()

    rows = set()
    for table, tags in TABLES.items():
        source_path = SOURCES[0] if table.startswith("Static") and table not in ("StaticHG", "StaticSS") else SOURCES[1]
        rows.update(parse_rows(texts[source_path], table, tags))

    ordered = sorted(rows)
    packed = [pack(row) for row in ordered]
    lines = [
        "// GENERATED by tools/gen_legality_gen4_static.py.",
        "// Source: PKHeX @ %s" % pkhex_source._REF,
        "// Sources: Encounters4DPPt.cs and Encounters4HGSS.cs static/gift tables.",
        "// FixedBall is preserved when specified by the source template; 0 means unrestricted.",
        "// Trades, external events and PokeWalker encounters are separate evidence layers.",
        "inline constexpr uint64_t kPackedGen4StaticEncounters[] = {",
    ]
    for i in range(0, len(packed), 5):
        chunk = ", ".join("0x%016xULL" % value for value in packed[i:i + 5])
        if i + 5 < len(packed):
            chunk += ","
        lines.append("    " + chunk)
    lines.append("};")
    lines.append("")

    if len(ordered) != 197:
        raise ValueError("expected 197 Gen IV static/gift rows, got %d" % len(ordered))

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))
    print("wrote %d Gen IV static/gift encounter rows to %s" % (len(ordered), OUT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
