#!/usr/bin/env python3
"""Generate Gen III Safari wild-encounter evidence from pinned PKHeX data.

PKHeX EncounterSlot3 derives Safari provenance from encounter location, not
Method-H slot type:
  R/S/E Safari Zone location = 57
  FR/LG Safari Zone location = 136

Only those source areas are distilled here. Method/slot/rate and lead metadata
are retained for later Method-H and lead-history work.
"""

from __future__ import annotations

import os
import struct

import pkhex_source

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "include", "Legality", "Gen3SafariEncounterData.inc")

GAMES = (
    ("ruby_gba", "Resources/legality/wild/Gen3/encounter_r.pkl", 0, 57),
    ("sapphire_gba", "Resources/legality/wild/Gen3/encounter_s.pkl", 1, 57),
    ("emerald_gba", "Resources/legality/wild/Gen3/encounter_e.pkl", 2, 57),
    ("firered_gba", "Resources/legality/wild/Gen3/encounter_fr.pkl", 3, 136),
    ("leafgreen_gba", "Resources/legality/wild/Gen3/encounter_lg.pkl", 4, 136),
)


def entries(data: bytes):
    if len(data) < 8:
        raise ValueError("BinLinker resource is truncated")
    count = struct.unpack_from("<H", data, 2)[0]
    offsets = struct.unpack_from("<%dI" % (count + 1), data, 4)
    for i in range(count):
        start, end = offsets[i], offsets[i + 1]
        if start > end or end > len(data):
            raise ValueError("BinLinker entry offset is invalid")
        yield data[start:end]


def parse_game(path: str, game_index: int, safari_location: int):
    with open(pkhex_source.pkhex_path(path), "rb") as handle:
        data = handle.read()

    rows = []
    for area_index, area in enumerate(entries(data)):
        if len(area) < 4:
            raise ValueError("truncated Gen III encounter area %d" % area_index)

        location = area[0]
        method = area[2]
        rate = area[3]
        if location != safari_location:
            continue

        slot_count = (len(area) - 4) // 10
        for slot_index in range(slot_count):
            offset = 4 + slot_index * 10
            rows.append((
                struct.unpack_from("<H", area, offset)[0],  # species
                location,
                area[offset + 4],  # min level
                area[offset + 5],  # max level
                method,
                area[offset + 2],  # form
                area[offset + 3],  # slot number
                rate,
                area[offset + 6],  # Magnet Pull index
                area[offset + 7],  # Magnet Pull count
                area[offset + 8],  # Static index
                area[offset + 9],  # Static count
                game_index,
            ))
    return rows


def main() -> int:
    rows = []
    for _name, path, game_index, safari_location in GAMES:
        rows.extend(parse_game(path, game_index, safari_location))
    rows.sort(key=lambda row: (
        row[12], row[1], row[0], row[4], row[6], row[2], row[3], row[5],
        row[7], row[8], row[9], row[10], row[11]
    ))

    lines = [
        "// GENERATED by tools/gen_legality_gen3_safari.py.",
        "// Source: PKHeX @ %s" % pkhex_source._REF,
        "// Resources: encounter_r/s/e/fr/lg.pkl (BinLinker Gen III wild slots).",
        "// Distilled rows are only PKHeX Safari locations: R/S/E=57, FR/LG=136.",
        "inline constexpr Entry kGen3SafariEntries[] = {",
    ]
    for row in rows:
        lines.append("    {%s}," % ", ".join(str(value) for value in row))
    lines.append("};")
    lines.append("")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))
    print("wrote %d Gen III Safari encounter rows to %s" % (len(rows), OUT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
