#!/usr/bin/env python3
"""Generate restricted anti-shiny Gen III BACD_R_A event-template evidence."""

from __future__ import annotations

import os
import re

import pkhex_source

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "include", "Legality", "Gen3BacdRaEventTemplateData.inc")
SOURCE = "Legality/Encounters/Data/Gen3/EncountersWC3.cs"

LANGUAGE = {
    "Japanese": 1,
    "English": 2,
    "French": 3,
    "Italian": 4,
    "German": 5,
    "Spanish": 7,
    "Korean": 8,
}
GENDER_RULE = {
    "Only0": 0,
    "Only1": 1,
    "RandD3": 2,
    "RandS3": 3,
    "RandS7": 4,
    "RandSG15": 5,
}


def cxx_u16(value: str) -> str:
    return 'u"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> int:
    with open(pkhex_source.pkhex_path(SOURCE), encoding="utf-8") as handle:
        source = handle.read()

    rows = []
    pattern = re.compile(
        r"new\(\s*(\d+)\s*,\s*(\d+)\s*,\s*([A-Z]+)\s*\)\s*\{([^}]*)\}"
    )
    for match in pattern.finditer(source):
        species, level, version, fields = match.groups()
        method = re.search(r"\bMethod\s*=\s*([A-Z0-9_]+)", fields)
        if not method or method.group(1) != "BACD_R_A":
            continue
        if version != "R":
            raise ValueError("BACD_R_A row is not fixed to Ruby origin")

        id_match = re.search(r"\bID32\s*=\s*(\d+)", fields)
        ot_match = re.search(r'\bOriginalTrainerName\s*=\s*"([^"]*)"', fields)
        gender_match = re.search(
            r"\bOriginalTrainerGender\s*=\s*([A-Za-z0-9_]+)", fields
        )
        moves_match = re.search(
            r"\bMoves\s*=\s*new\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)",
            fields,
        )
        if not id_match or not ot_match or not gender_match or not moves_match:
            raise ValueError("BACD_R_A row is missing fixed ID/OT/gender/moves evidence")

        gender_name = gender_match.group(1)
        if gender_name not in GENDER_RULE:
            raise ValueError("unsupported BACD_R_A OT-gender rule: " + gender_name)

        language_match = re.search(
            r"\bLanguage\s*=\s*\(int\)([A-Za-z]+)", fields
        )
        language = 0
        if language_match:
            language_name = language_match.group(1)
            if language_name not in LANGUAGE:
                raise ValueError("unsupported BACD_R_A language: " + language_name)
            language = LANGUAGE[language_name]

        id32 = int(id_match.group(1))
        moves = tuple(int(value) for value in moves_match.groups())
        rows.append((
            int(species),
            id32 & 0xFFFF,
            (id32 >> 16) & 0xFFFF,
            int(level),
            language,
            GENDER_RULE[gender_name],
            bool(re.search(r"\bFatefulEncounter\s*=\s*true", fields)),
            bool(re.search(r"\bRibbonNational\s*=\s*true", fields)),
            ot_match.group(1),
            moves,
        ))

    if len(rows) != 114:
        raise ValueError("expected 114 BACD_R_A event rows, got %d" % len(rows))

    rows.sort()
    lines = [
        "// GENERATED by tools/gen_legality_gen3_bacd_ra_events.py.",
        "// Source: PKHeX @ %s" % pkhex_source._REF,
        "// Source table: EncountersWC3.cs rows using PIDType.BACD_R_A.",
        "// All rows are Ruby-origin event gifts with restricted 16-bit BA-CD seeds.",
        "// Exact four-move distribution payloads are retained as positive event evidence.",
        "inline constexpr std::array<Entry, 114> kEntries{{",
    ]
    for species, tid, sid, level, language, gender_rule, fateful, ribbon_national, ot, moves in rows:
        lines.append(
            "    {%d, %d, %d, %d, %d, %d, %s, %s, %s, {%d, %d, %d, %d}}," %
            (species, tid, sid, level, language, gender_rule,
             "true" if fateful else "false",
             "true" if ribbon_national else "false", cxx_u16(ot), *moves)
        )
    lines.extend(["}};", ""])

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))
    print("wrote %d BACD_R_A event rows with moves and National Ribbon state to %s" % (len(rows), OUT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
