#!/usr/bin/env python3
"""Generate exact R/B and Yellow PK1 catch-rate tables from pinned PKHeX personal data."""

from __future__ import annotations

import os

import pkhex_source

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "include", "Legality", "Gen1CatchRateData.inc")
RECORD_SIZE = 0x1C
CATCH_RATE_OFFSET = 0x08


def rates(resource: str) -> list[int]:
    with open(pkhex_source.pkhex_path(resource), "rb") as handle:
        data = handle.read()
    if len(data) % RECORD_SIZE:
        raise ValueError("unexpected PersonalInfo1 resource size")
    result = [
        data[offset + CATCH_RATE_OFFSET]
        for offset in range(0, len(data), RECORD_SIZE)
    ]
    if len(result) != 152:
        raise ValueError("expected 152 PersonalInfo1 records")
    return result


def format_array(name: str, values: list[int]) -> list[str]:
    lines = [f"inline constexpr std::array<uint8_t, 152> {name}{{{{"]
    for i in range(0, len(values), 16):
        chunk = ", ".join(f"{v:3d}" for v in values[i:i + 16])
        if i + 16 < len(values):
            chunk += ","
        lines.append("    " + chunk)
    lines.append("}};")
    return lines


def main() -> int:
    rb = rates("Resources/byte/personal/personal_rb")
    yellow = rates("Resources/byte/personal/personal_y")
    lines = [
        "// GENERATED by tools/gen_legality_gen1_catch_rates.py.",
        f"// Source: PKHeX @ {pkhex_source._REF}",
        "// Resources: personal_rb, personal_y. CatchRate is byte 0x08 of each PersonalInfo1 record.",
        *format_array("kCatchRateRB", rb),
        "",
        *format_array("kCatchRateY", yellow),
        "",
    ]
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))
    print(f"wrote exact Gen I catch-rate tables to {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
