#!/usr/bin/env python3
"""Generate normal Pokemon Colosseum shadow encounter identity data from pinned PKHeX."""

from __future__ import annotations

import os
import re

import pkhex_source

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "include", "Legality", "Gen3ColoShadowEncounterData.inc")
SOURCE = "Legality/Encounters/Data/Gen3/Encounters3Colo.cs"

TEAM_SET = {
    "First": 0,
    "ColoMakuhita": 1,
    "Gligar": 2,
    "Murkrow": 3,
    "Heracross": 4,
    "Ursaring": 5,
}


def main() -> int:
    with open(pkhex_source.pkhex_path(SOURCE), encoding="utf-8") as handle:
        source = handle.read()

    marker = "internal static readonly EncounterShadow3Colo[] Shadow"
    start = source.find(marker)
    if start < 0:
        raise ValueError("missing normal Colosseum shadow table")
    end = source.find("public static readonly EncounterShadow3Colo[] EReader", start)
    if end < 0:
        raise ValueError("missing Colosseum e-Reader table boundary")
    body = source[start:end]

    rows = []
    pattern = re.compile(
        r"new\(\s*(\d+)\s*,\s*(\d+)\s*,\s*([A-Za-z0-9_]+)\s*\)\s*\{([^}]*)\}"
    )
    for match in pattern.finditer(body):
        shadow_index = int(match.group(1))
        team_name = match.group(3)
        fields = match.group(4)
        species = re.search(r"\bSpecies\s*=\s*(\d+)", fields)
        level = re.search(r"\bLevel\s*=\s*(\d+)", fields)
        location = re.search(r"\bLocation\s*=\s*(\d+)", fields)
        if not species or not level or not location:
            raise ValueError("incomplete Colosseum shadow row")
        if team_name not in TEAM_SET:
            raise ValueError("unknown normal Colosseum team set: " + team_name)
        rows.append((
            shadow_index,
            int(species.group(1)),
            int(level.group(1)),
            int(location.group(1)),
            TEAM_SET[team_name],
        ))

    if len(rows) != 80:
        raise ValueError("expected 80 normal Colosseum shadow rows, got %d" % len(rows))

    # Source audit invariant: exactly one persistent tuple is duplicated, Murkrow
    # Lv43 at location 67. The two rows carry different team histories and must
    # both survive generation so runtime matching can test either history.
    by_tuple = {}
    for row in rows:
        key = (row[1], row[2], row[3])
        by_tuple.setdefault(key, []).append(row)
    duplicates = {key: value for key, value in by_tuple.items() if len(value) > 1}
    if set(duplicates) != {(198, 43, 67)} or len(duplicates[(198, 43, 67)]) != 2:
        raise ValueError("unexpected duplicate Colosseum persistent-field tuples")

    lines = [
        "// GENERATED by tools/gen_legality_gen3_colo_shadows.py.",
        "// Source: PKHeX @ %s" % pkhex_source._REF,
        "// Source table: Encounters3Colo.Shadow (normal, excluding Japanese e-Reader rows).",
        "// Preserve duplicate persistent tuples: runtime must evaluate every matching team history.",
        "inline constexpr std::array<Entry, %d> kEntries{{" % len(rows),
    ]
    for row in rows:
        lines.append("    {%d, %d, %d, %d, %d}," % row)
    lines += ["}};", ""]

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))

    print("wrote %d normal Colosseum shadow rows to %s" % (len(rows), OUT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
