#!/usr/bin/env python3
"""Generate compact Gen IV PokéWalker encounter evidence from pinned PKHeX data."""

from __future__ import annotations

import os
import struct

import pkhex_source

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "include", "Legality", "Gen4PokewalkerEncounterData.inc")
RESOURCE = "Resources/legality/wild/Gen4/encounter_walker4.pkl"

def pack(course: int, slot: int, species: int, level: int, gender: int, moves: tuple[int, int, int, int]) -> int:
    value = species | (level << 9) | (gender << 16) | (course << 18) | (slot << 23)
    for index, move in enumerate(moves):
        value |= move << (26 + index * 9)
    return value

def main() -> int:
    with open(pkhex_source.pkhex_path(RESOURCE), "rb") as handle:
        data = handle.read()

    slot_size = 0xC
    slots_per_course = 6
    course_count = 27
    expected = slot_size * slots_per_course * course_count
    if len(data) != expected:
        raise ValueError(f"expected {expected} PokéWalker bytes, got {len(data)}")

    packed: list[int] = []
    for index in range(slots_per_course * course_count):
        offset = index * slot_size
        species, level, gender, m1, m2, m3, m4 = struct.unpack_from("<HBBHHHH", data, offset)
        packed.append(pack(index // slots_per_course, index % slots_per_course,
                           species, level, gender, (m1, m2, m3, m4)))

    lines = [
        "// GENERATED by tools/gen_legality_gen4_pokewalker.py.",
        f"// Source: PKHeX @ {pkhex_source._REF}",
        f"// Resource: PKHeX.Core/{RESOURCE}",
        "// 27 courses x 6 slots. Positive evidence only; course unlock/language history is separate.",
        "inline constexpr uint64_t kPackedGen4PokewalkerEncounters[] = {",
    ]
    for i in range(0, len(packed), 4):
        chunk = ", ".join(f"0x{value:016x}ULL" for value in packed[i:i + 4])
        if i + 4 < len(packed):
            chunk += ","
        lines.append("    " + chunk)
    lines.extend(["};", ""])

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))
    print(f"wrote {len(packed)} Gen IV PokéWalker encounter rows to {OUT}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
