#!/usr/bin/env python3
"""Regenerate exact Gen I-IV move picker Power/Accuracy/base-PP tables."""
from __future__ import annotations
import pathlib,re,struct,urllib.request
ROOT=pathlib.Path(__file__).resolve().parents[1]
OUT=ROOT/"include"/"Names"/"MoveBattleStats.h"
S={"gen1":("pret/pokered","d2704a63c26f9ba046ade877445216b3de0519a4","data/moves/moves.asm"),"gen2":("pret/pokecrystal","e058e4f50b3bbf7377e036b81c25a72c54656c5c","data/moves/moves.asm"),"gen3":("pret/pokeemerald","c587cc9e63f57ecc688adc00513499fc7f747ac6","src/data/battle_moves.h"),"gen4":("pret/pokeheartgold","9d8b7591f09b65804da2fb2dfd56f320633e0d36","files/poketool/waza/waza_tbl.narc")}
PREFIX="/**\n * MoveBattleStats.h - Exact in-generation move Power / Accuracy / base PP for Gen I-IV.\n * AUTO-GENERATED by tools/gen_move_battle_stats.py. DO NOT EDIT BY HAND.\n * Sources: pokered d2704a63c26f9ba046ade877445216b3de0519a4; pokecrystal e058e4f50b3bbf7377e036b81c25a72c54656c5c;\n * pokeemerald c587cc9e63f57ecc688adc00513499fc7f747ac6; pokeheartgold 9d8b7591f09b65804da2fb2dfd56f320633e0d36.\n * Raw move-table values only; Power is not final battle damage.\n */\n#ifndef NAMES_MOVE_BATTLE_STATS_H\n#define NAMES_MOVE_BATTLE_STATS_H\n#include <array>\n#include <cstdint>\n#include \"Enums/GameVersion.h\"\nnamespace Names {\nstruct MoveBattleStats { uint8_t power=0; uint8_t accuracy=0; uint8_t pp=0; };\nnamespace MoveBattleStatsData {\n"
SUFFIX="inline constexpr MoveBattleStats Gen4DPHypnosis{0,70,20}; // Diamond/Pearl only; Platinum/HGSS use 60 accuracy.\n} // namespace MoveBattleStatsData\ninline const MoveBattleStats* getMoveBattleStats(uint16_t moveId, Enums::GameVersion version) noexcept {\n    using Enums::GameVersion;\n    const auto group=Enums::getGameGroup(version);\n    const auto effective=group==GameVersion::Invalid ? version : group;\n    switch(effective){\n        case GameVersion::RBY: return moveId<MoveBattleStatsData::Gen1.size()?&MoveBattleStatsData::Gen1[moveId]:nullptr;\n        case GameVersion::GSC: return moveId<MoveBattleStatsData::Gen2.size()?&MoveBattleStatsData::Gen2[moveId]:nullptr;\n        case GameVersion::FRLG: return moveId<MoveBattleStatsData::Gen3.size()?&MoveBattleStatsData::Gen3[moveId]:nullptr;\n        case GameVersion::DP:\\n            if (moveId == 95) return &MoveBattleStatsData::Gen4DPHypnosis;\\n            return moveId<MoveBattleStatsData::Gen4.size()?&MoveBattleStatsData::Gen4[moveId]:nullptr;\\n        case GameVersion::PT: case GameVersion::HGSS: return moveId<MoveBattleStatsData::Gen4.size()?&MoveBattleStatsData::Gen4[moveId]:nullptr;\n        default: return nullptr;\n    }\n}\n} // namespace Names\n#endif\n"
def fetch(x):
 repo,ref,path=x
 with urllib.request.urlopen(f"https://raw.githubusercontent.com/{repo}/{ref}/{path}") as r:return r.read()
def asm(data,max_move):
 rows=[(0,0,0)]+[tuple(map(int,m)) for m in re.findall(r"^\\s*move\\s+[^,]+,\\s*[^,]+,\\s*(\\d+),\\s*[^,]+,\\s*(\\d+),\\s*(\\d+)",data.decode(),re.M)]
 assert len(rows)==max_move+1;return rows
def gen3(data):
 rows=[]
 for b in re.findall(r"\\[MOVE_[^\\]]+\\]\\s*=\\s*\\{(.*?)\\n\\s*\\},",data.decode(),re.S):
  p=re.search(r"\\.power\\s*=\\s*(\\d+)",b);a=re.search(r"\\.accuracy\\s*=\\s*(\\d+)",b);pp=re.search(r"\\.pp\\s*=\\s*(\\d+)",b)
  if p and a and pp:rows.append((int(p.group(1)),int(a.group(1)),int(pp.group(1))))
 assert len(rows)==355;return rows
def gen4(data):
 fat=16;fat_size=struct.unpack_from("<I",data,fat+4)[0];btnf=fat+fat_size;btnf_size=struct.unpack_from("<I",data,btnf+4)[0];start=btnf+btnf_size+8;rows=[]
 for move in range(468):
  a,b=struct.unpack_from("<II",data,fat+12+move*8);m=data[start+a:start+b];assert len(m)==16;rows.append((m[3],m[5],m[6]))
 return rows
def emit(name,rows):
 out=[f"inline constexpr std::array<MoveBattleStats, {len(rows)}> {name}{{{{"]
 for i in range(0,len(rows),8):out.append("    "+" ".join(f"{{{p},{a},{pp}}}," for p,a,pp in rows[i:i+8]))
 out.append("}};");return "\\n".join(out)+"\\n"
def main():
 g1=asm(fetch(S["gen1"]),165);g2=asm(fetch(S["gen2"]),251);g3=gen3(fetch(S["gen3"]));g4=gen4(fetch(S["gen4"]))
 assert g1[117]==(0,100,10) and g4[117]==(1,0,10) and g3[202]==(60,100,5) and g4[202]==(60,100,10) and g4[95]==(0,60,20)
 OUT.write_text(PREFIX+emit("Gen1",g1)+"\\n"+emit("Gen2",g2)+"\\n"+emit("Gen3",g3)+"\\n"+emit("Gen4",g4)+"\\n"+SUFFIX,encoding="utf-8",newline="\\n")
if __name__=="__main__":main()
