#!/usr/bin/env python3
"""Generate pinned Gen III PCNY machine-gift event rows from PKHeX binary data."""

from __future__ import annotations

import os
import struct

import pkhex_source

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "include", "Legality", "Gen3PcnyEventTemplateData.inc")
SOURCE = "Resources/legality/wild/Gen3/encounter_pcny.pkl"

def main() -> int:
    with open(pkhex_source.pkhex_path(SOURCE), "rb") as handle:
        data = handle.read()

    if len(data) != 600 or len(data) % 12:
        raise ValueError("expected 600-byte / 50-row PCNY resource, got %d bytes" % len(data))

    rows = []
    for offset in range(0, len(data), 12):
        species, = struct.unpack_from("<H", data, offset)
        level = data[offset + 2]
        distribution = data[offset + 3]
        moves = struct.unpack_from("<HHHH", data, offset + 4)
        rows.append((species, level, distribution, *moves))

    if len(rows) != 50:
        raise ValueError("expected 50 PCNY rows, got %d" % len(rows))
    if {row[2] for row in rows} != set(range(12)):
        raise ValueError("expected all 12 PCNY distribution groups")

    lines = [
        "// GENERATED by tools/gen_legality_gen3_pcny_events.py.",
        "// Source: PKHeX @ %s" % pkhex_source._REF,
        "// Source resource: encounter_pcny.pkl (50 rows x 12 bytes).",
        "// Moves are retained as source metadata only; current moves are mutable after receipt.",
        "inline constexpr std::array<Entry, 50> kEntries{{",
    ]
    for species, level, distribution, m1, m2, m3, m4 in rows:
        lines.append(
            "    {%d, %d, %d, {%d, %d, %d, %d}}," %
            (species, level, distribution, m1, m2, m3, m4)
        )
    lines.extend(["}};", ""])

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))
    print("wrote %d PCNY rows to %s" % (len(rows), OUT))
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
