#!/usr/bin/env python3
"""Generate compact Gen IV event-template legality evidence from pinned PKHeX wc4.pkl."""

from __future__ import annotations

import os
import struct

import pkhex_source

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "include", "Legality", "Gen4EventTemplateData.inc")
RESOURCE = "Resources/legality/mgdb/wc4.pkl"
PCD_SIZE = 0x358
PK_OFFSET = 8


def u16(data: bytes, off: int) -> int:
    return struct.unpack_from("<H", data, off)[0]


def u32(data: bytes, off: int) -> int:
    return struct.unpack_from("<I", data, off)[0]


def pk4_location(data: bytes, extended_off: int, dp_off: int) -> int:
    """Mirror G4PKM location selection: prefer the Pt/HGSS extended field."""
    extended = u16(data, extended_off)
    return extended if extended != 0 else u16(data, dp_off)


def main() -> int:
    with open(pkhex_source.pkhex_path(RESOURCE), "rb") as fh:
        raw = fh.read()
    if len(raw) % PCD_SIZE:
        raise ValueError("wc4.pkl is not a whole number of PCD records")

    rows = []
    for off in range(0, len(raw), PCD_SIZE):
        record = raw[off:off + PCD_SIZE]
        if u16(record, 0) != 1:  # GiftType4.Pokémon
            continue

        pk = record[PK_OFFSET:PK_OFFSET + 0xEC]
        # PKHeX's pinned event DB stores these PK4 payloads already decrypted.
        if u32(pk, 0x64) != 0:
            raise ValueError("unexpected encrypted PK4 payload in wc4.pkl")

        species = u16(pk, 0x08)
        if not 1 <= species <= 493:
            raise ValueError("invalid species in wc4.pkl: %d" % species)

        rows.append((
            species,
            u16(pk, 0x0C),
            u16(pk, 0x0E),
            u32(pk, 0x00),
            pk[0x84] & 0x7F,
            pk4_location(pk, 0x44, 0x7E) + 3000,
            max(pk[0x83], pk[0x86]),
            pk[0x40] >> 3,
            pk[0x17],
            pk[0x5F],
            pk[0x84] >> 7,
            bool(pk[0x40] & 1),
            u16(record, 0x150),
        ))

    if len(rows) != 247:
        raise ValueError("expected 247 Gen IV Pokémon templates, got %d" % len(rows))

    rows.sort()
    lines = [
        "// GENERATED by tools/gen_legality_gen4_events.py.",
        "// Source: PKHeX @ %s" % pkhex_source._REF,
        "// Source resource: PKHeX.Core/Resources/legality/mgdb/wc4.pkl",
        "// Pokémon PCD templates only (247 rows); non-Pokémon cards are excluded.",
        "inline constexpr EventTemplate kGen4EventTemplates[] = {",
    ]
    for row in rows:
        species, tid, sid, pid, level, met_location, ball, form, language, version, ot_gender, fateful, card_id = row
        lines.append(
            "    {%d, %d, %d, 0x%08xu, %d, %d, %d, %d, %d, %d, %d, %s, %d},"
            % (species, tid, sid, pid, level, met_location, ball, form, language,
               version, ot_gender, "true" if fateful else "false", card_id)
        )
    lines.append("};")
    lines.append("")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines))
    print("wrote %d Gen IV event templates to %s" % (len(rows), OUT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
