#!/usr/bin/env python3
"""Generate Pokemon XD recursive shadow team-lock evidence from pinned PKHeX source."""

from __future__ import annotations

import os
import re

import pkhex_source

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "include", "Legality", "Gen3XdShadowTeamLockData.inc")
ENCOUNTERS = "Legality/Encounters/Data/Gen3/Encounters3XD.cs"
TEAMS = "Legality/Encounters/Data/Gen3/Encounters3XDTeams.cs"
SHADOW = "Legality/Encounters/Data/Gen3/Encounters3XDShadow.cs"


def read(relpath: str) -> str:
    with open(pkhex_source.pkhex_path(relpath), encoding="utf-8") as handle:
        return handle.read()


def main() -> int:
    encounters = read(ENCOUNTERS)
    teams = read(TEAMS)
    shadow = read(SHADOW)

    marker = "internal static readonly EncounterShadow3XD[] Shadow"
    start = encounters.find(marker)
    if start < 0:
        raise ValueError("missing XD shadow encounter table")
    end = encounters.find("];", start)
    if end < 0:
        raise ValueError("unterminated XD shadow encounter table")
    encounter_body = encounters[start:end]

    encounter_rows = [
        (int(m.group(1)), m.group(3))
        for m in re.finditer(
            r"new\(\s*(\d+)\s*,\s*(\d+)\s*,\s*([A-Za-z0-9_]+)\s*\)\s*\{([^}]*)\}",
            encounter_body,
        )
    ]
    if len(encounter_rows) != 90:
        raise ValueError("expected 90 XD shadow rows, got %d" % len(encounter_rows))

    team_sets = []
    for match in re.finditer(
        r"public static readonly TeamLock\[\]\s+([A-Za-z0-9_]+)\s*=\s*\[([^\]]*)\]",
        teams,
    ):
        names = [x.strip() for x in match.group(2).split(",") if x.strip()]
        team_sets.append((match.group(1), names))
    if len(team_sets) != 72:
        raise ValueError("expected 72 XD team sets, got %d" % len(team_sets))

    starts = list(re.finditer(
        r"public static readonly TeamLock\s+([A-Za-z0-9_]+)\s*=\s*new\(",
        shadow,
    ))
    if len(starts) != 113:
        raise ValueError("expected 113 XD team variants, got %d" % len(starts))

    definitions = {}
    for i, match in enumerate(starts):
        finish = starts[i + 1].start() if i + 1 < len(starts) else len(shadow)
        block = shadow[match.start():finish]
        locks = []
        for lock in re.finditer(r"new NPCLock\(([^)]*)\)", block):
            args = [x.strip() for x in lock.group(1).split(",")]
            if len(args) == 1:
                locks.append((0, 0, 0, 1))
            elif len(args) == 2 and args[1] == "true":
                locks.append((0, 0, 0, 2))
            elif len(args) == 4:
                locks.append((int(args[1]), int(args[2]), int(args[3]), 0))
            else:
                raise ValueError("unsupported NPCLock: " + lock.group(1))
        if len(locks) > 5:
            raise ValueError("unexpected XD lock count")
        definitions[match.group(1)] = locks

    locks = []
    variants = []
    sets = []
    set_index = {}
    for index, (name, names) in enumerate(team_sets):
        set_index[name] = index
        variant_offset = len(variants)
        if len(names) > 9:
            raise ValueError("unexpected XD team variant count")
        for variant_name in names:
            member_locks = definitions.get(variant_name)
            if member_locks is None:
                raise ValueError("missing TeamLock " + variant_name)
            lock_offset = len(locks)
            locks.extend(member_locks)
            variants.append((lock_offset, len(member_locks)))
        sets.append((variant_offset, len(names)))

    if len(variants) != 113 or len(locks) != 389:
        raise ValueError("unexpected flattened XD team-lock dimensions")

    by_index = {}
    for shadow_index, team_name in encounter_rows:
        if team_name not in set_index:
            raise ValueError("unknown XD team alias " + team_name)
        prior = by_index.setdefault(shadow_index, team_name)
        if prior != team_name:
            raise ValueError("conflicting XD team alias for index %d" % shadow_index)
    if len(by_index) != 83:
        raise ValueError("expected 83 unique XD shadow indexes")

    index_map = [255] * 84
    for shadow_index in range(1, 84):
        team_name = by_index.get(shadow_index)
        if team_name is None:
            raise ValueError("missing XD shadow index %d" % shadow_index)
        index_map[shadow_index] = set_index[team_name]

    lines = [
        "// GENERATED by tools/gen_legality_gen3_xd_team_locks.py.",
        "// Source: PKHeX @ %s" % pkhex_source._REF,
        "// Sources: Encounters3XD.cs, Encounters3XDTeams.cs, Encounters3XDShadow.cs.",
        "// Positive-only recursive team-lock evidence. Search exhaustion is never an invalid verdict.",
        "inline constexpr std::array<LockEntry, %d> kLocks{{" % len(locks),
    ]
    lines += ["    {%d, %d, %d, %d}," % row for row in locks]
    lines += ["}};", "", "inline constexpr std::array<VariantEntry, %d> kVariants{{" % len(variants)]
    lines += ["    {%d, %d}," % row for row in variants]
    lines += ["}};", "", "inline constexpr std::array<TeamSetEntry, %d> kTeamSets{{" % len(sets)]
    lines += ["    {%d, %d}," % row for row in sets]
    lines += ["}};", "", "inline constexpr std::array<uint8_t, %d> kShadowIndexToTeamSet{{" % len(index_map)]
    for i in range(0, len(index_map), 12):
        lines.append("    " + ", ".join(str(x) for x in index_map[i:i + 12]) + ",")
    lines += ["}};", ""]

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))
    print("wrote %d team sets, %d variants and %d locks to %s" %
          (len(sets), len(variants), len(locks), OUT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
